### ISSUE TITLE
Duda Memoria/Stack/Heap

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2333/Foro-2020-2#1]
Hola, una consulta respecto a lo que pasa en el SO. Cuándo hablemos de que se utiliza cierta memoria en el computador y que existe un Stack/Heap en el computador, la memoria a la que se está accediendo es a la RAM? O a qué memoria se hace referencia?

Saludos

**Comment by VicenteMerino** [comment]
Pd: no está habilitado para que asignemos las labels.

**Comment by KnowYourselves** [comment]
Hola @VicenteMerino!

Gracias por avisar lo de las labels, lo arreglaremos lo antes posible.

Siempre hablamos de memoria RAM. Como tanto el Stack como el Heap contienen información que el programa requerirá en el futuro inmediato, sería impráctico que estuvieran fuera de la RAM.

Saludos!
