### ISSUE TITLE
Tippo de archivos Tests ejecutable

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2333/Foro-2020-2#10]
Hola, cuando implementamos `crexec`, no me queda muy claro qué es lo que debe ir como argumento ejecutable? Lo que pienso es que es por ejemplo un archivo binario compilado de C helloworld y eso usarlo como ejecutable válido? O con que tipo de archivos se probará la tarea. Además en la misma línea de lo anterior, supongo que podrñia pasar que no necesariamente debe existir un input en `crexec por ejemplo con hello world no necesita de inputs para ser ejecutado, es esto correcto?

**Comment by VicenteMerino** [comment]
Acabo de cachar que hay unos archivos de prueba en programs y ahí sale como se ejecutan, pero igual para saber ¿qué tipo de archivos son?

**Comment by KnowYourselves** [comment]
Hola @VicenteMerino!

El comando `crexec` recibe como input un ejecutable y sus argumentos. Por ejemplo, como bien dices en la carpeta `programs` hay varios programas de ejemplo para que prueben (veremos que hace cada uno en la ayudantía). El programa `helloworld` es exactamente eso, imprime `"Hello World!"` y no recibe argumentos, por lo cual para ejecutarlo haríamos `crexec helloworld`. El programa `sum` recibe una cantidad arbitraria de números e imprime su suma, por lo cual podríamos hacer `crexec sum 12 4 6 10`.

Espero se entienda.

Éxito!
