### ISSUE TITLE
Duda #define

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2333/Foro-2020-2#12]
En el código base de la tarea salen las línes:
`#define MAX_ARGS 255`
`#define MAX_LEN 255`

Cuando quiero volver a llamar esto (por ejemplo en un for), esto debe ser interpretado como qué tipo, un int?

**Comment by KnowYourselves** [comment]
Hola @VicenteMerino!

Son `ints`. Un caso de uso dentro de la tarea sería por ej:

```c
char some_string[MAX_ARGS];
int some_array[MAX_LEN];

for (int i = 0; i < MAX_LEN; i++)
{
    ...
}
```
Éxito!
