### ISSUE TITLE
Duda uso execlp y path a los ejecutables

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2333/Foro-2020-2#13]
Hola, no  me queda claro como debo poner los argumentos en un execlp para que funcione.

En mi código implementé un exec y probé usando 

`execlp("ls","ls", (char)*NULL);` 

y funcionó correctamente mostrándome los archivos del directorio, sin embargo, dado que me entregan un ejecutable personalizado no tengo claro como debería ser el argumento, he probado de varias formas:

`execlp("helloworld","helloworld", (char)*NULL);` 
`execlp("./programs/helloworld","helloworld", (char)*NULL);` 
`execlp("/programs/helloworld","helloworld", (char)*NULL);` 
`execlp("programs/helloworld","helloworld", (char)*NULL);` 

Y ninguno me está entregando resultado por lo que no se si estoy entendiendo mal el comando, o por qué no me está funcionando, si me pueden ayudar?

Además no se si debemos asumir que los ejecutables con los que se testee nuestro código, estarán todos en una carpeta `programs/` o no necesariamente? Afecta en algo el path del ejecutable?

Gracias

**Comment by KnowYourselves** [comment]
Hola @VicenteMerino!

Partiendo del final, **los programas a ejecutar con `crexec` estarán en la misma carpeta que `crsh`**, es decir, `crexec` recibe **ejecutables, no paths a ejecutables**. 

En cuanto a `execlp` la forma correcta es la siguiente:

```C
execlp("programs/helloworld", "helloworld", NULL);
```

No es necesario castear `NULL` a `char*` porque `NULL` ya es una dirección de memoria de por si. Si es que esta forma no te funciona, debe ser otro el error.  En la ayudantía veremos una forma de "debugear" más facilmente estos casos.

Éxito!

**Comment by VicenteMerino** [comment]
Lo que debería aparece es literalmente un Hello world! en la shell verdad? Es normal que desde la shell de linux, en la carpeta de programs si escribo  `./helloworld`me arroje el error `bash: ./helloworld: Permission denied`? Pienso que por ahí podría ir mi error.

**Comment by VicenteMerino** [comment]
Y respecto a lo primero que me constestaste, entonces lo correcto sería mover todos los ejecutables a la carpeta en que se compila crsh, en vez de programs?

**Comment by KnowYourselves** [comment]
Ese es el error entonces. No tienes el permiso para ejecutar los ejecutables, por lo cual `execlp` resultará en errror. Ese es un problema de tu sistema operativo, no del programa.

Prueba hacer `chmod +rwx helloworld` dentro de la carpeta `programs` y ve si te deja ejecutarlo.

Respecto a lo otro, si, eso sería lo correcto. Se lo pasamos así solo para que estuviera ordenado.

Éxito!

**Comment by VicenteMerino** [comment]
Buena, creo que funcionó. Tengo que repetirlo para todos los files verdad? O en el caso de los que reciben input debo agregar algo más?

**Comment by KnowYourselves** [comment]
Solo debes repetir el comando para el resto de los ejecutables, no afecta si estos reciben input o no.

**Comment by alexaptib** [comment]
@KnowYourselves Hola, hice tenia el mismo problema, e hice chmod +rwx helloworld y me dejo de dar error de permiso, pero ahora me sale -bash: ./helloworld: cannot execute binary file. que puedo hacer?
