### ISSUE TITLE
Validación del input en crexec

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2333/Foro-2020-2#14]
Podemos asumir que el usuario va a ingresar si o si un ejecutable después del crexec o hay que validarlo? Debemos asumir que dado que el usuario escribió un ejecutable correcto, el input asociado también lo escribirá correctamente? O esto hay que validarlo también?

**Comment by KnowYourselves** [comment]
Hola @VicenteMerino!

En cuanto a validación en términos generales, no se deben preocupar, pueden asumir que el usuario utilizará correctamente el programa.

En cuanto a `crexec` en el enunciado sale explícito que si se ingresa como primer argumento un ejecutable que no existe, se le debe indicar al usuario. En caso que el usuario ingrese un archivo que existe pero no es un ejecutable, o algún otro caso que cause que `exec` falle, deben tratarlo en su programa, pero no es necesario que informen al usuario al respecto.

Éxito!
