### ISSUE TITLE
Uso execvp con librería args

### ISSUE THREAD

**Issue by alobatog** [IIC2333/Foro-2020-2#15]
Hola! estuve intentando ejecutar los programas con execvp con el struct args de la forma:
`execvp(args->argv[0], args->argv);
 printf("EXEC FAILED: %s %s\n", args->argv[0], strerror(errno));`
 
Escribiendo en la consola `crexec sum 1 2` donde retorna:

`sum: 1: No such file or directory
sum: 2: No such file or directory`

Pero si escribo `crexec ./sum 1 2` retorna La suma es 3

**Comment by KnowYourselves** [comment]
Hola @alobatog!

Resulta que me inventé que había agregado el `./` en la librería `args`, por lo cual tienes dos opciones:

1. Ingresar los ejecutables con `./` al usar `crexec`.
2. Buscar alguna función `exec` que no requiera `./`.

Éxito!

**Comment by alobatog** [comment]
Gracias por la respuesta!!

**Comment by rakarachon** [comment]
Hola! Una duda, @KnowYourselves, cuando dices:

> 1. Ingresar los ejecutables con `./` al usar `crexec`.

lo entiendo como que, asumiendo que el ejecutable se encuentra en la misma carpeta que crsh, es el **usuario** quien debiera ingresar `crexec ./<nombre_ejecutable>` para que el programa funcione correctamente, es correcto esto? Y no que el "**código**" deba agregar `./` al inicio del nombre del ejecutable cada vez que el usuario use `crexec`.

Al final, mi duda apunta a que, ya que hay varias formas en la que podemos manejar el *path* de los ejecutables, así como más de una función `exec`, que por lo que entiendo también manejan los *path* de distinta manera, ¿existe una única forma que sería considerada "correcta" para efectos de la tarea? ¿o podemos usar cualquier mientras se explicite de alguna forma (comentarios en el código por ejemplo, o mensajes de "ayuda" entregados por el programa?

Gracias de antemano!

**Comment by KnowYourselves** [comment]
Hola @rakarachon!

Para efectos generales de programación uno tiene que elegir una función `exec` acorde a lo que queremos hacer. En esta tarea queremos ejecutar archivos, no paths. Hay funciones `exec` que reciben archivos y otras que reciben, path. En caso que usen la primera opción, se considerará correcto `crexec <ejecutable>`, en caso que usen la segunda opción, se considerá correcto `crexec ./<ejecutable>`

Éxito!

**Comment by rakarachon** [comment]
Perfecto, me quedó clarísimo, muchas gracias!!
