### ISSUE TITLE
Format Error al ejecutar binarios

### ISSUE THREAD

**Issue by nabenitez** [IIC2333/Foro-2020-2#16]
Hola! cuando ejecuto los binarios me tira el siguiente error: 

``` 
cannot execute binary file: Exec format error
```

Ejecutados desde **macOS**. También lo comenté en la ayudantía, por lo que leí es un error de compilación entre diferentes OS.
Agradecería si pueden subir los bin y que sí sean compatibles, o bien los .c y así compilarlos localmente.
Gracias! 😄

**Comment by KnowYourselves** [comment]
Hola @nabenitez!

Esta en proceso. Mandaremos un anuncio cuando lo hagamos. De momento pueden ustedes hacer programas simples para probrar!

Éxito!

**Comment by KnowYourselves** [comment]
Hola @nabenitez!

¿Podrías probar si [estos ejecutables](https://drive.google.com/file/d/1qq30Eujca--PKEs_utQGp_AyYT88xx-B/view?usp=sharing) te sirven?

Gracias!

**Comment by nabenitez** [comment]
Hola, @KnowYourselves, si sirven, muchas gracias!

Por si alguien más le ocurre:
* Primero dirá ``` permission denied ```. Asi que hay que correr ``` chmod +rwx namefile```. (Como en #13)
* También puede saltar el firewall de macOS que les dirá que no es de un desarrollador verificado (asi que hay que confiar 👀 ), ahí hay que darle permiso a la terminal en ```Preferences -> Security -> Privacy -> Developer Tools ```y clickear en ``` ``` ```terminal```.

**Comment by KnowYourselves** [comment]
Gracias por los pasos @nabenitez!

Respecto a la confianza, ¡No te preocupes! esos ejecutables solo sirven para que  ~~minemos bitcoin con sus computadores~~ prueben sus tareas.

Éxito!
