### ISSUE TITLE
[Enunciado] Duda con instrucción crexec

### ISSUE THREAD

**Issue by nabenitez** [IIC2333/Foro-2020-2#18]
Hola, 

Me queda una duda respecto a la siguiente frase: **"Correr uno o varios programas no debe congelar su shell"** y también a cómo se deben manejar los casos relacionados a este punto (creo).

En el caso del programa ```mustkill```, por lo que entiendo de la frase de arriba, en este caso la consola (crsh) se congela como se muestra aquí (*¿o se refieren a otra cosa con congelar?*):

![Screen Shot 2020-08-28 at 16 34 32](https://user-images.githubusercontent.com/42161839/91613520-aa788480-e94d-11ea-9a87-aa838de428b5.png)

La idea entonces es que la consola me permita *seguir ingresando comandos*, es decir, la siguiente línea a eso debería ser ``` $ ``` o debo *entrar desde otra shell*, ver qué procesos ha ejecutado **crsh** y poder ejecutar el comando para eliminar el proceso ```mustkill ``` (como se haría en la shell real). La misma duda con el caso ```stubborn```. 

Sé que mencionaron algo en la ayudantía, pero no me quedó claro.

Gracias!

**Comment by KnowYourselves** [comment]
Hola @nabenitez!

Eso es exactamente lo que **no debe pasar**.

Me explico, `crexec` debe crear  **un nuevo proceso** que ejecute el ejecutable ingresado. Esto quiere decir que cuando haces `crexec` creas el proceso e **inmediatamente después** vuelves a esperar _input_ del usuario. Como el ejecutable está en otro proceso, no importa si se queda pegado, si tiene un `while true` o si da _segfault_, debe ser un proceso aparte, distinto a `crsh`.

Éxito!

**Comment by nabenitez** [comment]
Vale! ahora si me queda claro. Es que era como contraintuitivo versus el funcionamiento de la shell cotidiana jaja.

**Comment by alexaptib** [comment]
@KnowYourselves me pasa algo similar con los $, pero no se congela, sigo podiendo ingresar nuevos comandos y si son ejecutados en nuevos procesos. Se me colocan dos $ seguidos en la linea que se ejeucta el archivo, entonces no esta el $ en la linea para ingresar el proximo pero si funciona al hacerlo. es un problema esto?

$
$ crexec stubborn
Command: crexec
Argc:    1
Argv:    stubborn
$
$ crexec helloworld
Command: crexec
Argc:    1
Argv:    helloworld 
$
$ $ Hello World!
crexec sum 4 6
Command: crexec
Argc:    3
Argv:    sum 4 6 
$
$ $ La suma es 10
(espacio en blanco para ingresar comando)
"

**Comment by nabenitez** [comment]
Me sumo a lo de @alexaptib, me pasa exactamente lo mismo, entonces no sé si estoy manejando mal los procesos o debería ser así.

**Comment by KnowYourselves** [comment]
Hola @alexaptib, @nabenitez!

Lo que pasa es que los ejecutables que les pasamos imprimen ese `$`, `helloworld` imprime  `$ Hello World!`, eso es todo! 

Lo esperable (indpendiente del ejecutable que utilicen) es que el output de su consola se desordene un poco, pero lo importante es que en ningún momento pierdan la capacidad de seguir ingresando comandos.

Éxito!

**Comment by nabenitez** [comment]
> Hola @nabenitez!
> 
> Eso es exactamente lo que **no debe pasar**.
> 
> Me explico, `crexec` debe crear **un nuevo proceso** que ejecute el ejecutable ingresado. Esto quiere decir que cuando haces `crexec` creas el proceso e **inmediatamente después** vuelves a esperar _input_ del usuario. Como el ejecutable está en otro proceso, no importa si se queda pegado, si tiene un `while true` o si da _segfault_, debe ser un proceso aparte, distinto a `crsh`.
> 
> Éxito!

@KnowYourselves  una duda respecto a esto, el esperar el _input_ del usuario ¿debe ser siempre desde el **primer** proceso creado o puede pasar que un **child** comience a recibir inputs?

**Comment by KnowYourselves** [comment]
Hola @nabenitez!

Mis disculpas, vi esto pero se me fue responder. No es necesario que te compliques de esa manera. El proceso padre puede ser la bash y recibir el input, no es necesario crear un proceso extra para eso.

Éxito!
