### ISSUE TITLE
Duda crlist

### ISSUE THREAD

**Issue by alobatog** [IIC2333/Foro-2020-2#19]
Hola!

Una duda sobre como hacer el comando crlist e ir guardando la info necesaria, sería mejor crear un struct tipo lista ligada o existe un comando que permita ver los hijos del proceso padre?

**Comment by KnowYourselves** [comment]
Hola @alobatog!

Puedes perfectamente crear un `struct` para organizar tu información, pero no es necesario que sea una lista ligada, puede ser un simple arreglo.

En cuanto a lo segundo, tienes acceso al PID de tus hijos cada vez que haces `fork`, tienes que guardar esa información de alguna forma.

Éxito!

**Comment by alobatog** [comment]
Pero con el arreglo tendría una cantidad fija de procesos que podría tener guardados en la lista no? En caso de que se creen más procesos que el largo del arreglo ya no serviría

**Comment by KnowYourselves** [comment]
Puedes asumir que no habrán más de 255 procesos corriendo.

Éxito!

**Comment by alobatog** [comment]
Oh buena, graciaas!

**Comment by VicenteMerino** [comment]
@KnowYourselves una duda, puedo tener máximo 255 procesos corriendo a la vez? o puedo asumir que son 255 procesos en total que se pueden ejecutar. Porque si por ejemplo corro inicialmente 255 procesos a la vez, estos irán a parar al arreglo que los guarda, pero en determinado momento va a terminar el proceso 60 por ejemplo. En ese caso debería modificar el arreglo de alguna forma para que almacene solo los activos? Ya que en ese caso me quedaría con 254 y podría volver a crear otro, pero el manejo de arreglos ya no sería tan simple y probablemente necesite otro tipo de estructuras.

**Comment by KnowYourselves** [comment]
Hola @VicenteMerino!

Son 255 procesos **a la vez**, no hay un máximo para el total.

En cuanto a como lograr esto, no es necesaria ninguna estructura de datos compleja, pero si te facilitaría el trabajo el uso de `struct`.

Éxito!
