### ISSUE TITLE
Programa se queda "pegado" en ejecutable

### ISSUE THREAD

**Issue by isiguelfand** [IIC2333/Foro-2020-2#20]
Hola! Después de correr `execvp(./helloworld, NULL)` me aparece en la consola `$ $ Hello World!`, con la doble $$, entonces no se puede poner otro comando (no aparece ningún `$` después ). No entiendo donde  podría estar el error, al parecer no está retornando de del ejecutable o del proceso correpondiente por alguna razón. 
Gracias!!

**Comment by KnowYourselves** [comment]
Hola @isiguelfand!

¿Estas haciendo `execvp` directamente, o después de haber hecho `fork`?

Quedo atento!

**Comment by isiguelfand** [comment]
Después de un fork!

**Comment by KnowYourselves** [comment]
Ah, me acabo de dar cuenta lo que pasa. Se mencionó en la issue #18. Es súper simple, los ejecutables que les pasamos imprimen `$`, por el ejemplo `helloworld` imprime `$ Hello World!`, por lo cual es esperable que el output de la consola se vea algo raro. 

Tomando esto en consideración ¿Si ingresas más _input_, este es procesado?

Éxito!

**Comment by isiguelfand** [comment]
Toda la razón! Gracias! No importa que se vea raro ?

**Comment by KnowYourselves** [comment]
Nooo, no importa.

Considerando lo que estan haciendo es super esperable que el output de consola se vea algo raro, asi que no importa, solo importa que nunca se pierda la capacidad de seguir ingresanso comandos.

Éxito!
