### ISSUE TITLE
Duda forma de argc

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2333/Foro-2020-2#21]
Hola, no me queda claro si argc tendrá el último argumento como un puntero a NULL para que pueda ser pasado directamente a execvp o esto debemos modificarlo nosotros?

**Comment by KnowYourselves** [comment]
Hola @VicenteMerino!

El `struct` pone el `NULL` al final de argv, no tienen que preocuparse de ponerlo.

Éxito!
