### ISSUE TITLE
Cantidad de programas a ejecutar

### ISSUE THREAD

**Issue by Marialuisaclaro** [IIC2333/Foro-2020-2#22]
Hola!
Para la tarea 1, podemos asumir que la cantidad de programas que se ejecutaran son menos de 255? Para poder guardarlos en un array. O tenemos que implementar una lista ligada con struct y todo eso?

Gracias!

**Comment by KnowYourselves** [comment]
Hola @Marialuisaclaro!

Puedes asumir que como máximo habrán 255 procesos simultáneamente.

Éxito!

**Comment by cristobalwelch** [comment]
En esa misma linea, eso significa que podrían haber más de 255 procesos, pero no de manera simultánea? Por ejemplo, si se crean 255 procesos, se terminan 5, y se vuelven a crear otros 5. Eso es un escenario posible? O asumimos que no se van a crear más de 255 procesos? 

Gracias!

**Comment by KnowYourselves** [comment]
Hola @cristobalwelch!

No hay límite en la cantidad total de procesos que se pueden crear.

Éxito!
