### ISSUE TITLE
Error al crear puntero a Struct en un array

### ISSUE THREAD

**Issue by isiguelfand** [IIC2333/Foro-2020-2#23]
Hola! No me manejo mucho en C y estoy siguiendo los videos del minicurso para poder hacer la tarea. Estoy tratando de hacer un array de punteros a structs, pero al crear el puntero me tira el error `error: variable-sized object may not be initialized` (cuando trato de compilar el código). El puntero lo estoy creando exactamente de la misma forma que muestran en el video de Structs, la única diferencia es que en este caso es un elemento de un arreglo, entonces no sé donde podría estar el problema. 
Gracias!!

**Comment by KnowYourselves** [comment]
Hola @isiguelfand!

¿Podrías poner un ejemplo de código? 

Si no puedes poner un ejemplo sin revelar parte de tu tarea te pido porfavor que me envíes un correo.

Éxito!

**Comment by isiguelfand** [comment]
Te envio un correo mejor!
