### ISSUE TITLE
Duda código base + precisión tiempos crlist

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2333/Foro-2020-2#24]
Hola tengo un par de dudas sobre la tarea:

1. En el código base, cuando estoy dentro del whilet(true) y se hace args_get() esto evita que vuelva a pasar a otra iteración hasta que el usuario le de un argumento o está constantemente en un loop?

2. Tengo duda sobre la precisión qué precisión debe tener el tiempo de ejecución que se pide y como se va a medir si es correcta o no. Por ejemplo en mi caso cuando llamo a crlist, debo buscar en un arreglo cada proceso que aún está corriendo, por lo que este for agrega un poco de tiempo antes que se muestre en pantalla el tiempo de ejecución, por lo cual podría hacer la medición del tiempo, tanto antes de la búsqueda, como en el momento que lo encuentre, pero independiente de lo anterior, siempre habrá un poco de sesgo en la medición. Podemos obviar estos casos?

**Comment by KnowYourselves** [comment]
Hola @VicenteMerino!

Respecto a tus dudas:
1. El programa se queda en `args_get` hasta que se le envíe un SIGINT o se ingrese _input_.
2. La precisión es en segundos con un margen de error de 1. Por ejemplo, si tienes corriendo los 255 procesos, hacer el for para encontrar el último proceso va agregar un delay _insignificante_, pero que podría causar que digas un tiempo muy levemente equivocado. Mientras se note que efectivamente se esta contabilizando el tiempo bien basta.

Éxito

**Comment by VicenteMerino** [comment]
Respecto el tiempo, este debe estar con presición decimal? Lo que pasa es que investigué el uso de las función `time()` y el problema que tiene es que mide el tiempo de segundos que han pasado desde 1970, por lo que no tiene precisión decimal para medir diferencias, entonces no sé si el tiempo con que medirán será de forma decimal o entera en cuanto a su precisión. Una alternativa que revisé es usar `clock()` midiendo los tiempos y ponderizando por `CLOCKS_PER_SEC`, pero al parecer como es el tiempo que un proceso mantiene activo, y en `args_get` se queda pegado, entonces me dan tiempos que no corresponden (porque son tiempos relativos al programa y no globales como en el caso de `time`). Por lo tanto no se me ocurre de que otra forma se podría medir tiempos con una mayor cantidad de cifras de precisión.

**Comment by KnowYourselves** [comment]
Es tiempo en segundos, no importa la precisión decimal.

Éxito!

**Comment by VicenteMerino** [comment]
Buenísimo, gracias!!

**Comment by cchauriye** [comment]
Hola! Respecto al tiempo, el enunciado dice tiempo de ejecución. Eso significa que es literalmente el tiempo que la CPU pasó en ese proceso o es la diferencia simple entre el tiempo de inicio y el tiempo en que se ejecuta crlist? En otras palabras, es real time o user time?

**Comment by KnowYourselves** [comment]
Hola @cchauriye!

Es solo cuanto tiempo ha pasado entre que se hizo `crexec` del proceso y `crlist`.

Éxito!
