### ISSUE TITLE
Duda de crkill

### ISSUE THREAD

**Issue by maogaz** [IIC2333/Foro-2020-2#25]
Para el comando de crkill el signal sera algo del estilo "SIGKILL" o "SIGTERM", o seran numeros como en el ejemplo del enunciado?
Suponemos que los signals seran algo logico?

**Comment by KnowYourselves** [comment]
Hola @maogaz!

Puedes asumir que el usuario usará bien el programa, solo tienes que hacerte cargos que salen explicitos en el enunciado, por ejemplo, que en `crexec` se ingrese un ejecutable que no existe o en `crkill` un PID que no fue generado por `crexec`. En cuanto a los argumentos de `crkill` siempre serán números.

Éxito!

**Comment by maogaz** [comment]
A que se refieren estos numeros? Nose como interpretarlos. @KnowYourselves

**Comment by KnowYourselves** [comment]
Me explico,

El comando es el siguiente: `crkill <signal> <PID>`.

Donde `<signal>` y `<PID>` son números, en específico:
* `<signal>` representa la señal a enviar, de hecho, las señales en C son [solo números](http://www.yolinux.com/TUTORIALS/C++Signals.html).
* `<PID>` representa el PID del proceso, es decir, su identificador único que le asignó el sistema operativo.

Un ejemplo de uso del comando sería `crkill 2 153`,  que significa "envía la señal 2 (`SIGINT`) al proceso 153". 

Finalmente, la librería lectora de argumentos guarda estos argumentos como `char*` y deberás pasarlos a `int` para poder utilizarlos correctamente. Para eso te recomiendo ver el capítulo de Strings del curso Intro a C.

Espero se entienda mejor así!

Éxito!

**Comment by maogaz** [comment]
Gracias!
