### ISSUE TITLE
Hacer referencia a campo de un struct

### ISSUE THREAD

**Issue by isiguelfand** [IIC2333/Foro-2020-2#26]
Hola! Estoy tratando de hacer referencia al campo de un struct al definir otro struct, pero que el segundo no cambie cuando cambia el primero. Es decir, quiero que el campo de mi struct_2 sea igual a un campo de mi struct_1 al momento de definir la instancia del struct_2, y que este no cambie si cambia el campo correspondiente del struct_1. En este caso, es un "string" y se me ocurre copiar letra por letra, pero supongo que debe existir una manera más eficiente de hacer esta referencia.
Gracias!!

**Comment by KnowYourselves** [comment]
Hola @isiguelfand!

Como los "strings" en C no son más que arrays de char, es decir, que son punteros, la única forma de "copiarlos" es pasar, uno por uno, el contenido de un arreglo hacia el otro. Ojo que este proceso es **extremadamente eficiente** debido a como el lenguaje interactua con el computador.

En fin, para realizar el proceso, puedes hacerlo manualmente, o mediante el uso de funciones como `strcpy` de la librería `string.h`.

Éxito!

**Comment by isiguelfand** [comment]
Gracias! Justo eso estaba haciendo. Podemos asumir que los nombre de los ejecutables que van a usar en la tarea tienen cierta cantidad de caracteres ?

**Comment by KnowYourselves** [comment]
Puedes asumir que el nombre del ejecutable no será de más de 255 caracteres.

Éxito!

**Comment by isiguelfand** [comment]
Muchas gracias! Perdón por la insistencia, pero aún con el strcpy no me funciona. Si uso una variable auxiliar al final tengo el mismo problema, y si trato de hacer el strcpy directo al atributo me arroja segmentation fault 11.

**Comment by KnowYourselves** [comment]
Prueba ejecutando tu programa con valgrind para ver que te dice respecto al error. Si es que no logras detectar que está mal, puedes enviarme un correo.

Éxito!

**Comment by isiguelfand** [comment]
Gracias! Te voy a enviar un mail.

**Comment by miguelramirezv** [comment]
[Hice la issue #44  con este problema para más detalle y para que no se marcara como resuelto]

Hola! Creo que mi duda va un poco en la linea de esto que estoy teniendo problemas definiendo un campo como char* en mi estructura pero después no la encuentra. 

Esto es por ejemplo que pueda acceder a ella haciendo struct1 -> campo (sí struct1 es un puntero) pero siempre me entrega algo vacío. Y mi duda más grande es que pasa lo siguiente:
- struct1 -> otro_campo sí lo encuentra
- struct1 -> campo sí lo encuentra en el init, pero después lo entrega como vacío

Es decir, sí lo encuentra y lo guarda, pero después como que lo pierde y no lo encuentra pero solo este campo ¿Qué podría estar pasando?
