### ISSUE TITLE
Proceso en espera

### ISSUE THREAD

**Issue by Tito0906** [IIC2333/Foro-2020-2#27]
Hola! Tengo una duda sobre cuáles son los estados bajo los cuales un proceso se considera "ejecutando". En específico, no entiendo si se considera un programa como "ejecutando"  a cualquier estado aparte de terminado o sólo en estado running. Por ejemplo, supongamos que un proceso se queda esperando (sin hacer nada) durante 20 segundos, de tal forma que no ocupe CPU en ese tiempo. Si yo hago crlist, ¿debería aparecer ese programa dentro de la lista?

**Comment by KnowYourselves** [comment]
Hola @Tito0906!

Para efectos de esta tarea no les importa ese tipo de detalles. El tiempo es solo cuanto ha pasado desde que se hizo `crexec` hasta que se hizo `crlist`, independiente de cualquier otra cosa.

Esto quiere decir que lo único que importa en cuanto al estado de ejecución de los procesos al momento de hacer `crlist` es si es que estos han terminado.

Éxito!

**Comment by Tito0906** [comment]
Oka! Muchas gracias!!!
