### ISSUE TITLE
crkill 2 <PID>

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2333/Foro-2020-2#28]
Cuando uso el comando que aparece en el título (2=SIGINT) para cualquier PID se debe comportar como un crexit? o son cosas distintas?

Que si no me equivoco esto sería para mandar un SIGINT solo para el proceso PID, cuando hago ctrl+c, esto es un SIGINT pero para el padre, por eso debo manejar ese caso y serían casos distintos. Corríjanme si estoy equivocado.

**Comment by KnowYourselves** [comment]
Hola @VicenteMerino!

Lo que se menciona al final de `SIGINT` se refiere **exclusivamente** a `crsh`, es decir que si `crsh` recibe un `SIGINT` debe ser equivalente a que ese ejecute `crexit`.

Piensalo de esta forma, como `crkill` manda una señal a procesos iniciados con `crexec` no tienes forma posible de influir como estos van a tratarla.

Éxito!
