### ISSUE TITLE
Duda variables globales

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2333/Foro-2020-2#29]
Hola, estaba tratando de conectar una señal a una función y ver como pasar otro argumento, pero buscando en internet, vi que esto no se podía. Es por ello que vi que lo que tenía que hacer era declarar la variable como una global. Ahora bien, cuando inicializo esta variable (un arreglo), lo recorro con un for y asigno un NULL a cada posición. Ahora bien, si lo quiero hacer de forma global, debo definir el arreglo fuera de mis funciones, pero no se si el for funcione correctamente al no estar en ninguna función (main). De qué forma forma podría inicializar un array que actúe de forma global? O si o si debería hacerse esa inicializacion dentro del main?

**Comment by KnowYourselves** [comment]
Hola @VicenteMerino!

Hasta donde tengo entendido debiése funcionar perfectamente. Eso si, es más recomendable mantener tu información dentro de una función, y modificar "flags" globales cuando se activen señales, pero ese tipo de implementación, si bien mejor, es opcional.

Éxito!
