### ISSUE TITLE
Video Clase 12-Agosto

### ISSUE THREAD

**Issue by rakarachon** [IIC2333/Foro-2020-2#3]
Hola! En el anuncio en canvas con los links a los videos de las dos primeras clases, el link para la clase del miércoles 12 lleva al video de la clase del lunes 10. ¿Podrían por favor corregir el link de la clase del miércoles? 😁  

Muchas gracias de antemano!

**Comment by KnowYourselves** [comment]
Hola @rakarachon!

Toda la razón. Acabamos de modificar el anuncio, disculpas por la molestia.

Saludos,
Raúl Álvarez

**Comment by rakarachon** [comment]
Gracias! 🙌
