### ISSUE TITLE
Tiempo de espera crexit

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2333/Foro-2020-2#30]
Hola, cuando se gatilla un crexit si o si debo esperar los 15 segundos? o en el caso de que todos los programas terminen satisfactoriamente antes de los 15 segs, se debe terminar inmediatamente?

**Comment by KnowYourselves** [comment]
Hola @VicenteMerino!

Tu programa espera a que los procesos terminen **o** pasen 15 segundos. Si todos los procesos terminan, le programa debiese terminar inmediatamente.

Éxito!
