### ISSUE TITLE
Valgrind Leaks

### ISSUE THREAD

**Issue by cchauriye** [IIC2333/Foro-2020-2#31]
Hola!

Al correr valgrind me sale esto:

![Captura de Pantalla 2020-08-31 a la(s) 00 15 33](https://user-images.githubusercontent.com/31393605/91682345-3e4d7a80-eb1f-11ea-9313-220eff785605.png)

Eso se considera 0 leaks y 0 errores? Me cupo la duda porque no hay "definitely lost" pero si unos "reachable" y "supressed".

Gracias!

**Comment by KnowYourselves** [comment]
Hola @cchauriye!

Debiese salirte 0 en todo. Prueba en el servidor, ya que si usas Mac puede haber falsos positivos.

Éxito!

**Comment by Cadagan** [comment]
Solo como duda en esa linea, en Windows Subsystem for Linux no nos pueden dar esos mismos falsos positivos de igual forma verdad? No hay problemas en usar WSL?

**Comment by KnowYourselves** [comment]
Hola @Cadagan!

Una WSL1 podría tener (y de hecho un tiempo tuvo) leaks. Hasta donde tengo entendido una WSL2, debido al hecho de ser una máquina virtual, no debiese tener leaks.

De todas formas, la palabra final respecto a tu manejo de memoria es el servidor. Si en el servidor no hay leaks, todo bien.

Éxito!

**Comment by cchauriye** [comment]
Gracias!
