### ISSUE TITLE
Cómo correr tarea en el servidor, uso de makefile

### ISSUE THREAD

**Issue by bpardobravo** [IIC2333/Foro-2020-2#32]
Hola, estoy un poco confundido respecto a las cosas que hay que subir al servidor para poder ejecutar mi tarea en este, vs lo que hay que subir para la entrega oficial.

Si subo mi tarea tal como esta (con el makefile que nos pasaron, en la misma carpeta en la cual esta la carpeta src, con crsh dentro de src, main.c y la carpeta args dentro de esta, etc), ¿debería correr bien mi tarea en el servidor?

Si esto es así, para dejar la carpeta T1 como se pide en el enunciado, ¿hay que modificar makefile, ya que ahora makefile y main.c estan en la misma carpeta? ¿o hay que hacer la misma ruta de carpetas, dentro de T1, incluyendo los args.c y args.h dentro de la carpeta args?

**Comment by KnowYourselves** [comment]
Hola @bpardobravo!

**Solo debes subir el código base y el makefile, ningún binario**. Si hay algo que no sea un archivo .c, .h o Makefile en tu carpeta T1, es descuento (a excepción de un README.md, en caso que quieras redactar uno).

En cuanto a la estructura, da lo mismo, lo único que obligamos es que todo este contenido en la carpeta T1, y si yo entro a esa carpeta y hago `make` tu tarea compile.

Éxito!
