### ISSUE TITLE
Duda crexit - Cantidad de crl + C

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2333/Foro-2020-2#33]
Hola, en crexit el programa debe poder ser capaz de ejecutar infinitamente ctrl-C hasta que termine, es decir debe ser capaz de procesar correctamente 10 ctrl C seguidos hasta que se espera que mande el SIGKILL, o después de la primera señal ctrl-C o crexit, puedo asumir que el programa no va a recibir nada?

**Comment by KnowYourselves** [comment]
Hola @VicenteMerino!

Yo debiese poder enviar 100000000 `SIGINT` a tu programa seguidos. Este debiése "pescar" el `SIGINT` solo si estaba fuera de `crexit`.

Éxito!
