### ISSUE TITLE
Duda SIGINT - Opciones para terminarse

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2333/Foro-2020-2#34]
Hola, cuando mando SIGINT a un porceso puedo asumir que solo una de las siguientes dos cosas pueden pasar:

1. Que el proceso termine inmediatamente.
2. Que el proceso no termine.

Es decir, para el caso de crexit, es suficiente saber que el proceso no terminó inmediatamente y después de los 15 segundos lo deba terminar con SIGKILL? O puede pasar que mi proceso no termine inmediatamente, y después de 8 segundos por ejemplo, este termine y deba estar constantemente revisando si todos mis procesos han terminado o no?

**Comment by KnowYourselves** [comment]
Hola @VicenteMerino!

Debido a que la naturaleza de la señal `SIGINT` es un "para por favor", hay procesos que al recibir esta señal liberan memoria y hacen otras cosas antes de efectivamente terminar, por lo cual se pueden demorar.

En ese sentido si a los 3.754 segundos después de haber enviado los `SIGINT` todos los procesos terminan, entonces tu programa debiese terminar en vez de esperar lo 15 segundos enteros.

Éxito!
