### ISSUE TITLE
Error enCtrl C

### ISSUE THREAD

**Issue by Marialuisaclaro** [IIC2333/Foro-2020-2#35]
Hola!
Al ejecutar crexit mi programa funciona perfectamente, pero me pasa que al hacer Ctrl C, llamo a una funcion que hace **exactamente** lo mismo que crexit, pero luego se queda pegado y no termina. Si esque escribo cosas o pongo muchos enter a veces sale, pero osino se queda pegado. Que puedo hacer? Llevo mucho tiempo con este problema.

Gracias!

**Comment by KnowYourselves** [comment]
Hola @Marialuisaclaro!

Haz lo siguiente:

1. Abre dos terminales.
2. En una ejecuta `htop`.
3. En otra ejecuta `crsh`.
4. Haz Ctrl+C/envíale un `SIGINT` a `crsh` y mira lo que pasa en `htop`.

Si el proceso efectivamente ya no sale en `htop` significa que efectivamente terminó, solo que tu bash se quedo con las instrucciones `scanf` y `fgets` de la librería `args` en cola.

Cuéntame que tal!

**Comment by Franco1605** [comment]
Hola, entonces se debe interrumpir de alguna forma ambas acciones ?

**Comment by KnowYourselves** [comment]
Hola @Franco1605!

A que te refieres exactamente?

**Comment by Franco1605** [comment]
Porque me está pasando exactamente lo mismo que a la compañera, y he estado buscando cómo terminar el programa definitivamente, incluso he encontrado "volatile sig_atomic_t", pero sigue quedándose pegado.

**Comment by KnowYourselves** [comment]
¿Probaste los pasos que le recomendé a tu compañera?

De ser así, ¿Qué pasó?

**Comment by Franco1605** [comment]
Si hago ctrl c, en una consola, se queda pegado. En htop, crsh aparece como sleep. Si luego, donde corri crsh hago alguna acción y pongo enter, se termina crsh y ya no aparece en htop.

**Comment by KnowYourselves** [comment]
Entonces está bien, es exactamente lo que describí en el primer comemntario que hice.

**Comment by Franco1605** [comment]
Pero hay alguna forma de que no pase eso? o sea, que directamente apretando ctrl+c termine el programa simplemente ?

**Comment by KnowYourselves** [comment]
Debido a como funciona `scanf` y como esta implementado la librería `args`, no, no se puede. Con otras funciones y algunas magias negras de C es posible, pero se escapa del _scope_ del curso.

**Comment by Franco1605** [comment]
Entonces, solo para corroborar: si apreto ctrl-c y la consola se queda pegada, el usuario deberá si o si hacer otra acción y apretar enter para finalmente terminar el programa ?

**Comment by KnowYourselves** [comment]
Efectivamente!
