### ISSUE TITLE
Servidor

### ISSUE THREAD

**Issue by Marialuisaclaro** [IIC2333/Foro-2020-2#36]
Hola!
Estoy subiendo mi tarea al servidor y me gustaria saber como puedo eliminar archivos ahi. Por ejemplo los ejecutables helloworld y otros.
Por otro lado, subí mi tarea al servidor y luego hice unos cambios, al subir mi tarea de nuevo no se actualiza. ¿Como puedo borrar toda la carpeta para poder subirla de nuevo?

Gracias

**Comment by KnowYourselves** [comment]
Hola @Marialuisaclaro!

Como el servidor esta en un ambiente UNIX puedes utilizar los comandos típicos para hacer lo que pides. 

Para eliminar un archivo debes hacer `rm nombre_archivo`, mientras que para eliminar una carpeta debes hacer `rm -r nombre_carpeta`.

Éxito!
