### ISSUE TITLE
Error al correr en servidor

### ISSUE THREAD

**Issue by cchauriye** [IIC2333/Foro-2020-2#37]
Hola!

Al correr mi programa en el servidor me dice "-bash: ./helloworld: Permission denied". También me pasó en mi computador y lo solucioné con comandos que vi en otra issue, pero me da miedo hacerlo en el servidor y dejar la embarrada 😮 . ¿Qué hago?

Gracias!

**Comment by KnowYourselves** [comment]
Hola @cchauriye!

Los comandos que salen en esa issue solo modifican los permisos de un archivo **no es posible que dejes la embarrada con ese comando**. Prueba dando permisos de ejecución al ejecutable. Si no funciona, tendrías que crear tu propio código y compilarlo en el servidor para probar.

Éxito!
