### ISSUE TITLE
Forma más limpia de matar al padre

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2333/Foro-2020-2#38]
Hola, me gustaría cual es la forma más limpia de matar al programa principal. Lo que estoy haciendo es usar un handler y tengo dos opciones para terminar el programa: usar un exit o usar un SIGINT con dirección al handler por "default". Haciendo lo segundo y corriendo con valgrind me genera el siguiente mensaje:

![Screenshot from 2020-08-31 18-33-35](https://user-images.githubusercontent.com/47841749/91775206-85d41500-ebb8-11ea-9060-45229114808a.png)

No es precisamente un error, pero no se si sea una forma "limpia" de hacerlo, por lo cual me gustaría saber qué es lo más correcto para terminar un programa, o si esta forma está correcta.

**Comment by KnowYourselves** [comment]
Hola @VicenteMerino!

En ningún momento habría que "matar" al programa principal. Este siempre debería terminar _gracefully_. 

Ahora, lo que esta pasando en lo que muestras es que tu cuando haces ctrl+c se envía `SIGINT` a `crsh` y a todos sus hijos, entre ellos `stubborn`, por lo cual se imprime `"$ Nome puedes detener ;)"`.

Si hicieras **una vez ctrl+c** con `stubborn` corriendo debiése pasar lo siguiente:

1. Se imprime  `"$ Nome puedes detener ;)"` dos veces, una porm el ctrl+c y otro por el `SIGINT` que `crexit` debiése enviar.
2. Pasan 15 segundos.
3. Tu programa envía `SIGKILL` a `stubborn`.
4. El programa principal libera su memoria y llega al final de su función `main`/hace `exit`.

Si tu programa cumple con eso, entonces está bien.

Éxito!

**Comment by VicenteMerino** [comment]
Lo que pasa es que de esa forma estaba teniendo complicaciones para salir del loop, ya que cuando recibía el ctrl +C se mandaba a un handler, pero al terminar no podía salir del while(true), ya que no podía hacer un break desde el handler y si bien se limpiaban los procesos hijo, el main no terminaba, por eso traté de forzar el término del proceso principal desde el handler, una vez se limpiaran los otros procesos. En caso de un crexit no es complicado (basta con un break después de la señal para romper el loop), pero con un ctrl + C no es tan simple salir del loop ya que llega cuando estoy pegado en args_get() y no puedo hacer un break en el handler.

**Comment by KnowYourselves** [comment]
Entonces estás teniendo un problema de modelación. Es completamente posible terminar _gracefully_, tu programa no debiese terminar por haber recibido una señal `SIGINT`, debiese terminar por haber llegado al final de `main` o haber hecho `exit`. Como logres eso, es parte de la tarea.

Éxito!

**Comment by VicenteMerino** [comment]
creo que se me acaba de ocurrir algo. Las únicas dos formas de salir va a ser un ctrl C o un crexit verdad?

**Comment by KnowYourselves** [comment]
Exactamente, esas son las únicas dos formas. Ojo que ambas deben comportarse exactamente de la misma manera, en términos de lógica del programa hacer ctrl+C debiése ser equivalente a hacer `crexit`.
