### ISSUE TITLE
Enviar señal a proceso zombie

### ISSUE THREAD

**Issue by Tito0906** [IIC2333/Foro-2020-2#39]
Hola! Tengo una duda de qué sucede si envío una señal a un proceso zombie. Por lo que entiendo, una vez que un proceso comienza con crexec, el programa padre no hace wait de ningún tipo hasta que se haga crlist. Por esta razón, es posible tener procesos zombies cuando se ejecutan otros comandos en la "cruz shell". Según esto mismo, si no he hecho crlist y hago kill, entonces voy a estar enviando una señal a un proceso zombie. ¿Es esto válido?? Si no lo es, ¿cómo debe ocurrir?

**Comment by KnowYourselves** [comment]
Hola @Tito0906!

Es válido en el sentido que C lo permite. Si revisas la [manpage de kill](https://www.man7.org/linux/man-pages/man2/kill.2.html) puedes ver que dentro de los errores que tiene definido uno de estos es enviarle una señal a un proceso  que se ha detenido, que no existe o que está como _zombie_, por lo cual al hacer `kill` a un _zombie_ el método retorna -1 y setea el valor de errno.

En general es considerada buena práctica **no intentar contactar a los muertos** y hacer `wait` antes de hacer `kill`. Si quieres entender más profundamente por que mandar una señal a un proceso _zombie_ no produce ningún error muy terrible, te recomiendo leer [esto](https://unix.stackexchange.com/questions/256926/what-happends-when-sending-sigkill-to-a-zombie-process-in-linux#:~:text=To%20your%20question%3A&text=The%20signal%20is%20%22delivered%22%20to,process%20is%20that%20process%20struct.).

Éxito!

**Comment by Tito0906** [comment]
Hola! Si había leído que se podía, por eso no sabía que se debía hacer en estricto rigor cuando se llamaba crkill con un proceso zombie jajaja. 

Muchas gracias por contestar rápido!!
