### ISSUE TITLE
Videos de Clases

### ISSUE THREAD

**Issue by BenjaPrograma** [IIC2333/Foro-2020-2#4]
Hola! me parece que la forma en la que están subiendo las grabaciones de clases actualmente es un poco desordenada. Creo que es mejor si lo hacen como en las ayudantías, donde comparten un link a una carpeta en google drive donde después se suben las grabaciones.
La clase de hoy cuando se encontrará subida aprox?

Saludos!

**Comment by KnowYourselves** [comment]
Hola @BenjaPrograma!

Dicho y hecho. En breve les enviaremos el link donde se irán subiendo las clases.

Saludos!

**Comment by BenjaPrograma** [comment]
Muchas gracias!

**Comment by BenjaPrograma** [comment]
Hola! Me esta pidiendo acceso con mi cuenta UC el link.

**Comment by KnowYourselves** [comment]
Eso es porque esta seteado para que solo pueda entrar gente con cuenta UC, debes estar conectado a google con tu cuenta UC para poder acceder al drive.

PD: No cierres las issues, nosotros las cerraremos manualmente después de un tiempo

**Comment by BenjaPrograma** [comment]
Estoy logeado con mi cuenta UC

**Comment by KnowYourselves** [comment]
Entonces inicia sesión desde el link, con eso te conectarás a drive desde tu cuenta UC y podrás acceder.

Saludos!

**Comment by BenjaPrograma** [comment]
No me deja
![Screenshot_452](https://user-images.githubusercontent.com/26238496/90707573-e46acc00-e265-11ea-8667-292db2474eb2.png)

**Comment by KnowYourselves** [comment]
Y ahora?

**Comment by BenjaPrograma** [comment]
Ahora sí! Gracias
