### ISSUE TITLE
[MacOS] crkill 9 PID no mata el proceso

### ISSUE THREAD

**Issue by baaldana** [IIC2333/Foro-2020-2#40]
Hola, no sé por qué pasa pero al enviar la señal de ```SIGKILL``` a un proceso stubborn este no muere, sino que permanece en mi htop, pero deja de actualizarse (TIME+ se queda congelado y el uso de CPU también). La única forma de que desaparezca es que luego de haber ejecutado el ```crkill``` ejecute ```crlist```. ¿Qué puedo hacer al respecto? He visto que en algunos foros dicen que siempre es necesario hacer un ```wait```, pero cuando aplico un ```SIGKILL``` desde htop al stubborn lo mata sin problemas.

![image](https://user-images.githubusercontent.com/42224818/91792698-212eaf80-ebe4-11ea-8049-c8972b1abc3f.png)

UPDATE: ejecuté un ```SIGKILL``` desde el htop al mismo proceso stubborn de la foto y tampoco lo mató. Solo lo mata cuando el proceso crsh ya no está corriendo.

**Comment by KnowYourselves** [comment]
Hola @baaldana!

Considerando lo que describes, creo que esto apunta a un problema con `htop`, es probable que el proceso efectivamente haya terminado, solo que no se ve actualizado en la tabla de procesos.

Éxito!
