### ISSUE TITLE
Interrumpir args_get() con ctrl + c

### ISSUE THREAD

**Issue by Tito0906** [IIC2333/Foro-2020-2#41]
Hola! Estoy teniendo problemas con cerrar el programa sin fallas de memoria al hacer ctrl+c. Mi problema es que cada vez que trato de interrumpir args_get() se queda esperando. Revisé la función y al parecer, fgets() detiene la ejecución e incluso se reinicia después de que uso un timer para interrumpirlo. Probé también con alarm y sigalarm pero sigo teniendo el mismo problema con fgets. Al parecer, fgets necesita que presione enter para dejarme salir del programa. Podrían darme un poco más de info sobre cómo interrumpir args_get() sin tener fallas de memoria con ctrl+c? porque no tengo problemas con crexit, pero el ctrl + c no logro que funciona. 

Agradezco de antemano la respuesta!

**Comment by Tito0906** [comment]
Hola! Logré hacer que funcionara!! 

Muchas gracias de todas formas!

**Comment by Franco1605** [comment]
Estoy teniendo el mismo problema ! Alguna guía por favor !

**Comment by KnowYourselves** [comment]
Hola @Franco1605!

Tienes dos opciones:

1. Hacer todo desde la función que recibe la señal y salir del programa ahí con exit.
2. Asumir que despues de hecho el ctrl+c el usuario debe apretar enter en la consola.

Saludos!

**Comment by Tito0906** [comment]
Hola @KnowYourselves ! Pero en el caso de asumir que debes apretar enter, que pasa si cuando se hace ctrl + c hay que hacer enter, pero cuando hago crexit no lo hago? no sería diferente y estaría malo en ese caso?

**Comment by KnowYourselves** [comment]
Holav @Tito0906!

Técnicamente hablando, cuando haces `crexit` el usuario debió haber apretado enter, asi que todo está bien.

Éxito!

**Comment by Tito0906** [comment]
Hola @KnowYourselves !
Okok! Muchas gracias! Había hecho algo bastante mas complejo para que funcionara sin enter, pero si se puede hacer con, entonces lo cambio para que sea más simple.
