### ISSUE TITLE
Output diferente con y sin Valgrind

### ISSUE THREAD

**Issue by cristobalwelch** [IIC2333/Foro-2020-2#42]
Hola!

Estaba revisando mi código antes de subirlo al servidor y me di cuenta que cuando hago crlist, lo que se imprime cambia dependiendo si estoy corriendo el programa con o sin valgrind. Cuando lo corro con valgrind, se imprime todo bien. Cuando lo corro sin valgrind, el nombre del proceso no se imprime de manera correcta y aparecen símbolos raros (adjunto una foto de ejemplo). 

Saben porqué podría ser esto?

Gracias! 

![Valgrind](https://user-images.githubusercontent.com/30981540/91876032-3e966480-ec4a-11ea-8fab-dd982f60301c.jpg)
![No Valgrind](https://user-images.githubusercontent.com/30981540/91876058-46ee9f80-ec4a-11ea-9980-d08a1da16f94.jpg)

**Comment by KnowYourselves** [comment]
Hola @cristobalwelch!

Sucede que tienes un error de memoria, eso es lo que te muestra valgrind al inicio. Sucede que valgrind es capaz de arreglar ese tipo de errores, pero no funcionará en ejecución normal, por lo cual debes arreglarlo.

Éxito!
