### ISSUE TITLE
Definir variables globales y calloc

### ISSUE THREAD

**Issue by isiguelfand** [IIC2333/Foro-2020-2#43]
Hola! En mi programa, dentro de la función run() tenía un array de punteros para el cual necesitaba usar calloc. Ahora, tuve que crear una nueva función para manejar las señales (como mostraron en la ayudantía) y estoy teniendo muchos problemas para que quedé bien definido el array, ya que lo estoy intentando de crear fuera de ambas funciones y no me funciona, tampoco me funciona solamente declararlo fuera de ambas funciones. No entiendo cual sería la manera correcta de hacerlo.
Muchas gracias!

**Comment by KnowYourselves** [comment]
Hola @isiguelfand!

Puedes simplemente, fuera de toda función, de forma global declarar tu arreglo, por ejemplo de la forma `MiStruct **arreglo;`. Como es una variable global puedes acceder a esta en todo el programa, por lo cual en algun momento deberás hacer `arreglo = malloc/calloc`.

Éxito!

**Comment by isiguelfand** [comment]
Gracias! No sé por qué no me funcionaba pero lo logré!
