### ISSUE TITLE
Valor erróneo de atributo char* (cambia o se elimina)

### ISSUE THREAD

**Issue by miguelramirezv** [IIC2333/Foro-2020-2#44]
Hola! Tengo una duda con un atributo que estoy definiendo en mi estructura de tipo char*. 

Mi estructura cuenta con atributos de tipo int y de tipo char*, los cuales al hacer el init() los imprimo para asegurarme que están asignados:
- printf( %i, estructura -> campo) para los int
- printf( %s, estructura -> campo) para los char*

Y funciona todo bien. El problema que tengo es que después corriendo el programa al acceder a mi estructura y imprimir, con los mismos comando de arriba, se me imprimen correctamente los int pero los char* se imprimen vacíos.

Creo que tal vez el lugar donde apunta char* se me cambia o puede ser que el campo se borra. Pero no sé muy bien que pasa ni como saberlo. He puesto mil printfs pero no logro encontrarlo.

**Comment by KnowYourselves** [comment]
Hola @miguelramirezv!

Probablemente lo que te pasa es qu estas haciendo algo de la forma "estructura->nombre = args->argv[0]". El problema con esto es que args es un puntero de punteros en el heap, es tan solo una dirección de memoria y al hacr eso l nombre de tu proceso queda aputnando a exactamente la misma dirección que `argv`.

El problema con esto es que a la siguiente iteración cuando se pida argumentos esa memoria será liberada por la librería `args` por lo cual `estructura->nombre` habrá quedado apuntando a memoria que podría tener cualquier cosa, por eso el "cambio".

Ahí lo que tienes que hacer es copiar caracter por caracter el contenido de un string haica el otro, mediante `strcpy` o algún proceso similar.

Éxito!

**Comment by miguelramirezv** [comment]
Muchas gracias! Eso era exactamente!!

**Comment by figarcia3** [comment]
Hola! Estoy aplicando la solucion pero me sigue tirando error, de hecho me da segmentation fault al utilizar strcpy. Que puede ser? 
![error1](https://user-images.githubusercontent.com/48328327/91928801-fbb8a900-ecaa-11ea-8030-f1d59b490ba2.png)

**Comment by KnowYourselves** [comment]
Hola @figarcia3!

¿De casualidad tienes definido el valor en tu `struct` como un `char*`?

Éxitoo!
