### ISSUE TITLE
Copiar un string a una variable de otra struct

### ISSUE THREAD

**Issue by BenjaPrograma** [IIC2333/Foro-2020-2#45]
Hola! Estoy teniendo problemas para copiar el nombre del ejecutable de args->argv[0] hacia una variable de una estructura propia que estoy usando, al definirla en mi struct.h estoy haciendo  char* process_name, y le asigno a traves de strcopy el valor de argv[0], sin embargo a la hora de hacer printf de este valor me tira cualquier cosa, unos tildes, espacios en blancos, letras random, etc.

Saludos!

**Comment by KnowYourselves** [comment]
Hola @BenjaPrograma!

Lo que sucede es que al definir `char * process_name` es un puntero que apunta a memoria no inicializada, es decir, C no sabe cuanto es el tamaño del puntero ni que información tiene, por lo cual hacer strcpy hacia el es comportamiento no definido.

Lo que debes hacer es definir el process_name, con un tamaño preexistente, por ejemplo 255, de la forma `char process_name[255]`.

Éxito!

**Comment by BenjaPrograma** [comment]
Me pasa que en ese caso me tira esto:
```
src/crsh/linked_list.c:26:24: error: assignment to expression with array type
   26 |     node->process_name = process_name;
```
Y process_name lo tengo como un argumento que recibe el init de mi nodo de la forma: char*

**Comment by KnowYourselves** [comment]
Eso se debe a que debes utilizar `strcpy` para pasar el contenido de `process_name` a `node->process_name`.
