### ISSUE TITLE
Control + C diferente comportamiento con Valgrind

### ISSUE THREAD

**Issue by miguelramirezv** [IIC2333/Foro-2020-2#46]
Hola! Estoy teniendo la verdad dos problemas con Valgrind. Primero te cuento que sin Valgrind todo funciona bien, pero cuando uso Valgrind me pasa que:

1.- No me funciona el ctrl + c, tengo que usar crexit aunque tengan las dos la misma lógica

2.- Tengo muchos leas (te lo cuento porque puede estar relacionado)

No sé porque tantos leaks si libero todos los mallocs que pido, pero algo puede tener de relación con el control c.
Muchas gracias de antemano!!

**Comment by KnowYourselves** [comment]
Hola @miguelramirezv!

Respecto al punto 2. valgrind no es la fuente de los leaks, es quien te informa de los leaks que ya había previamente en tu programa. Al final del output de vlagrind puedes ver instrucciones para ejecutar el programa para que te diga las líneas donde ocurrieron los leaks.

Respecto al ctrl+c es probable que al usar valgrind y hacer ctrl+c le lleguen dos SIGINT a tu programa y por eso no funcione.

Éxito!

**Comment by miguelramirezv** [comment]
Gracias! Dale voy a ver esas líneas, te pasaste!
