### ISSUE TITLE
Problema con valgrind y concepto control c no entendido.

### ISSUE THREAD

**Issue by nicoparraguez** [IIC2333/Foro-2020-2#47]
Hola, cada vez que ejecuto el programa con valgrind y luego hago control+c (aun no progamo crexit) me sale lo siguiente en valgrind  
![foto](https://user-images.githubusercontent.com/30676212/91924714-7086e580-eca1-11ea-8cd7-d19d25e5e8c9.JPG)

lo que significa que no se ni de donde salen esos bloques que no se eliminan si no estoy creando nada, ni llamando un malloc o algo asi :( , no entiendo que sucede

**Comment by KnowYourselves** [comment]
Hola @nicoparraguez!

Puedes correr `valgrind --leak-check=full --show-leak-kinds=all ./crsh` y de dirá exactamente donde sucedió el leak.

Éxito!

**Comment by nicoparraguez** [comment]
El problema es que cuando uno realiza control+c no se sale del while y solo deja de ejecutar programa por lo cual no se leen las lineas free(args) por lo que solo paso por el hecho de ejecutar esta short cut.

**Comment by KnowYourselves** [comment]
Se considerará correcto si debo apretar enter para que tu programa termine después de haber hecho ctrl+c.

Éxito!
