### ISSUE TITLE
Formato de Entrega Tarea

### ISSUE THREAD

**Issue by BenjaPrograma** [IIC2333/Foro-2020-2#48]
Hola! Tengo dudas de como entregar la tarea, puedo tener una subcarpeta dentro de la carpeta T1, por ejemplo la carpeta OBJ y la carpeta SRC? y que pasa si tengo otros archivos .c y .h, van subidos en la misma carpeta? Los archivos tienen que tener algun nombre en particular?

Saludos!

**Comment by KnowYourselves** [comment]
Hola @BenjaPrograma!

Debes cumplir las siguientes condiciones:

1. Dentro de tu carpeta de usuario debe haber una carpeta llamada `T1`.
2. Dentro de `T1` debe haber un `Makefile` y el código base.
3. Dentro de `T1` no deben haber binarios ni ejecutables (la carpeta `obj` son binarios).
4. Al posicionarme en `T1` y hacer `make` tu tarea debe compilar.

Éxito!

**Comment by BenjaPrograma** [comment]
Gracias!

**Comment by JaviFerrada** [comment]
Hola! subi la tarea antes de las 14.00 pero se me olvidó borrar los binarios, los borre recien, tengo que contestar igual el formulario de entrega atrasada?

**Comment by KnowYourselves** [comment]
Hola @JaviFerrada!

Si crees que tu nota sin descuento es inferior a 6,25 te conviene entregar tarde, sino, no.

Éxito!
