### ISSUE TITLE
descuento por atraso t1

### ISSUE THREAD

**Issue by lzalaquett** [IIC2333/Foro-2020-2#49]
Hola, quiero saber cuanto es el descuento por entregar atrasado, no se si está especificado en alguna parte.

saludos

**Comment by ararojas** [comment]
En el enunciado dice que baja 0,75 por día la nota máxima alcanzable, pero no se hace descuento directo sobre tu nota. Si la entregas mañana sería máximo un 6,25.

**Comment by KnowYourselves** [comment]
Muchas gracias por la respuesta @ararojas!

Efectivamente, se encuentra al final del enunciado.
