### ISSUE TITLE
No me puedo conectar al servidor

### ISSUE THREAD

**Issue by tpcantergiani** [IIC2333/Foro-2020-2#5]
Buenos días!
Estaba intentado ingresar al servidor del curso, lo intente mediante la consola y filezilla, pero en ambos no logra entrar, dándome un error de "Connection timed out".
Intente varias cosas, pero, no he podido solucionarlo.

**Comment by lzalaquett** [comment]
A mi me pasó lo mismo!

**Comment by tpcantergiani** [comment]
> A mi me pasó lo mismo!

Están apagados los servidores del DCC

**Comment by KnowYourselves** [comment]
Exactamente. Estarán apagados hasta aproximadamente las 19:00 horas. Ojo que usualmente si tienen acceso a internet y de lleno no se les conecta es altamente probable que sea porque el servidor esta caído.

Saludos!
