### ISSUE TITLE
Resultados valgrind (tira resultados entremedio)

### ISSUE THREAD

**Issue by ararojas** [IIC2333/Foro-2020-2#50]
Hola!
Cuando corro mi programa con valgrind a veces valgrind me muestra sus resultados antes de que termine el programa. Después cuando termina el programa también me los muestra. Quería saber si miran todos los resultados o solo los últimos ya que en los últimos no tengo errores pero en los anteriores a veces si. Yo creo que esto pasa porque al finalizar el programa correctamente soluciono los errores que se mostraban antes.
Gracias y saludos!

**Comment by KnowYourselves** [comment]
Hola @ararojas!

Estás confundide. Valgrind ejecuta tu programa mientras monitera como este utiliza memoria. Si tu programa cae en un memory error (leer memoria inválida, escribir en memoria inválida, utilizar if con punteros no inicializados, etc) valgrind te avisará durante la ejecución. Estos errores descuentan puntaje en manejo de memoria y pueden causar que tu programa caia en comportamiento no definido.

Al final de su ejecución Valgrind te muestra un resumen de tu uso de memoria y si tienes leaks, es decir memoria que no liberaste, esto no tiene nada que ver con lo anterior.

Saludos!
