### ISSUE TITLE
Clases L31/08 y M02/09

### ISSUE THREAD

**Issue by rakarachon** [IIC2333/Foro-2020-2#51]
Hola! Podrían por favor subir las grabaciones de las clases de esta semana recién pasada? (Lunes 31 de Agosto y Miércoles 2 de Septiembre)

Muchas gracias de antemano! 😄

**Comment by cruz** [comment]
He subido todas justo después de la clase. Están aquí: [https://drive.google.com/drive/u/2/folders/1srBdlUhkZgQpWR5egVNzjhwtNuMaSjbp](https://drive.google.com/drive/u/2/folders/1srBdlUhkZgQpWR5egVNzjhwtNuMaSjbp
)
Ese link está referencia desde Canvas también

**Comment by rakarachon** [comment]
Gracias profesor!
