### ISSUE TITLE
¿Todos los procesos alcanzan a terminar?

### ISSUE THREAD

**Issue by viantirreau** [IIC2333/Foro-2020-2#52]
Hola!

Me quedó la duda si podemos asumir que todos los procesos podrían alcanzar a ejecutarse dentro de su _deadline_ con la asignación de tiempo óptima. Me refiero a un caso como el proceso `PROCESS1_RAUL`, que tiene un _deadline_ de 120 pero sus _bursts_ tardan 150 según el ejemplo de input. En caso de que efectivamente haya algunos que no se logren cumplir dentro del _deadline_, ¿cómo sería el criterio de priorización?

Gracias desde ya!

**Comment by KnowYourselves** [comment]
Hola @viantirreau!

Eso depende netamente de la cantidad de CPUs que tengas y los _bursts_ del proceso. En el ejemplo del enunciado con 3 o más CPUs el único proceso que no alcanzaría su _deadline_ sería `PROCESS1_RAUL`.

En cuanto al criterio, siempre es el mismo. Si un proceso pasa a `READY` y no quedan CPUs disponibles, se deben revisar los procesos actualmente siendo ejecutados y ver si es que conviene interrumpir a uno y a cual. Ustedes tienen que ver cual es el criterio, pero este depende siempre del valor del _deadline_ usando el `PID` para romper posibles empates.

Éxito!

**Comment by viantirreau** [comment]
Perfecto!!

Es decir, si vence el _deadline_ de un proceso, ¿sería deseable que siga ejecutando con atraso y no lo detenemos?

Gracias nuevamente!

**Comment by KnowYourselves** [comment]
Exactamente. Piensa en el _deadline_ como un punto en una línea de tiempo. Si estás en el tiempo 50, y tienes un proceso con _deadline_ 20 que todavía no termina y te llega un proceso con _deadline_ 51, todavía tiene mayor prioridad el proceso con _deadline_ 20.

**Comment by viantirreau** [comment]
10/10 :raised_hands: 

Gracias por la explicación!!

**Comment by Cadagan** [comment]
Habrá alguna especie de descuento si en alguna tarea por ejemplo, algún proceso que de forma optima alcanzaba a cumplir con su deadline, pero se pasa del tiempo de igual forma tomando más ticks que lo necesario? igual según yo no debiese pasar (al final los "criterios óptimos" ya nos los dieron en bandeja escritos y detallados), pero para aclarar ese punto

**Comment by KnowYourselves** [comment]
Hola @Cadagan!

Hay puntaje asignado a que tu _scheduler_ sea efectivamente óptimo. Si no lo es hiciste un _scheduler_ distinto al descrito en el enunciado.

Éxito!
