### ISSUE TITLE
Cantidad ráfagas de CPU

### ISSUE THREAD

**Issue by alobatog** [IIC2333/Foro-2020-2#53]
Hola! puedo asumir que la cantidad de ráfagas de CPU será como máximo 255? o no hay un límite en la cantidad de ráfagas de CPU que puede tener un proceso?

**Comment by KnowYourselves** [comment]
Hola @alobatog!

Tal como se vio en la ayudantía puedes asumir que todos los valores máximos (excepto por las lineas del archivo de input) serán 255.

Éxito!

**Comment by alobatog** [comment]
Gracias!!
