### ISSUE TITLE
Duda flujo estado procesos

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2333/Foro-2020-2#54]
Hola, si tengo dos procesos:
Proceso1 Tiempo_llegada:0, CPU_BURST1: 20, IO_BURST1:10, CPU_BURST2:10, Deadline 100
Proceso2 Tiempo_llegada:0, CPU_BURST1:20, IO_BURST1: 10, CPU_BURST2:10, Deadline 200

Aquí ambos entran a la cola al mismo tiempo y se elegirá el que tenga el deadline más cercano, es decir Proceso1, pero cuando se gaste la primera ráfaga de CPU, entonces pasará a consumir la ráfaga de I/O y paralelamente Proceso2 empezará a consumir su primera ráfaga de CPU. Mi pregunta es, que si el Proceso1 termina su primera ráfaga de I/O, esto será en el instante 30, pero al Proceso2 aún le quedarán 10 de tiempo para terminar de consumir su primer CPU burst, en este caso se debe interrumpir dicha ejecución y el cpu pasaría a Proceso1 dado que tiene deadline menor? O se espera a que termine su primer CPU_BURST para pasarle el control?

**Comment by KnowYourselves** [comment]
Hola @VicenteMerino!

En el caso que describes efectivamente debiése ocurrir una interrupción. 

Éxito!

**Comment by VicenteMerino** [comment]
@KnowYourselves y si ocurre esa interrupción el Proceso2 pasaría a consumir su primera ráfaga de IO, o debe esperar a consumir su primera ráfaga de CPU para pasar a consumir IO?

**Comment by KnowYourselves** [comment]
Pasa de estado `RUNNING` a `READY`, ya que todavía no esta en una ráfaga de IO.

Éxito!
