### ISSUE TITLE
Ejecutable solución

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2333/Foro-2020-2#55]
Hola, si bien no se van a subir tests para probar el programa para no sesgarnos. No se si es posible que nos puedan subir los ejecutables binarios de la solución para poder probar por nuestra cuenta los tests que nosotros realicemos y comprobar que el output de nuestra solución sea correcta?

**Comment by KnowYourselves** [comment]
Hola @VicenteMerino!

Que comprueben que su _scheduler_ esta funcionando de forma correcta es parte de lo que queremos evaluar, por lo cual no subiremos los binarios.

Éxito!
