### ISSUE TITLE
Strcpy / Direcciones de memoria

### ISSUE THREAD

**Issue by cchauriye** [IIC2333/Foro-2020-2#59]
Hola! 

Estoy usando strcpy y, tal como se mencionó en ayudantía, se me están sobreescibiendo las direcciones y no logro solucionarlo. ¿Alguna idea? 

Tengo este código dentro de un for:
![Captura de Pantalla 2020-09-13 a la(s) 23 12 08](https://user-images.githubusercontent.com/31393605/93036712-02cea800-f617-11ea-85e0-55ad2a610915.png)

En cada iteración al final hago: process->name = name , siendo process-> name un char*.

Gracias!

**Comment by KnowYourselves** [comment]
Hola @cchauriye!

El problema es que al hacer `process->name = name` estás haciendo exactamente lo que no deberías, tratando los strings como simples punteros. La variable `name` quedo correctamente guardada en el _stack_ gracias a `strcpy`, pero luego al hacer `process->name = name` estas igualando los  punteros, no copiando el string, por lo cual cuando `name` sea eliminado del _stack_ `process->name` quedará apuntando a una dirección invalida.

Éxito!

**Comment by cchauriye** [comment]
Hola!

Gracias por lo rápido! Intenté haciendo strcpy(process->name, name), pero me tira segmentation fault.

**Comment by cchauriye** [comment]
Lo logré gracias!
