### ISSUE TITLE
AC01 P15 y P16

### ISSUE THREAD

**Issue by GbPoblete** [IIC2333/Foro-2020-2#6]
Hoola! 

Tengo dos preguntas muy cortitas con estas preguntas. La primera, la P15 la última alternativa está bien que diga Match o debiera ser Mac?

La segunda pregunta, es si la P16 está mal escrita y falta considerar una alternativa; o ambas frases son parte de la misma alternativa?.

Gracias! Que estén muy bien :D

**Comment by cruz** [comment]
Hola @GbPoblete 

Sobre P15. Está bien escrito. **Mach** es el nombre de un sistema operativo (antiguo, pero importante). Búscalo en google y encontrarás información de sus principios de diseño y qué rol cumplió. También encontrarás algo en la lectura de [Evolución de los sistemas operativos](https://cursos.canvas.uc.cl/courses/17300/modules/items/362647).

Sobre P16, estaba escrita un poco rara. La alternativa de THE tenía una afirmación (sobre la que hay que averiguar si es verdad o no) y una frase que originalmente era de ayuda para facilitar la búsqueda. Tal como quedó, parecía que esa última frase era parte de la afirmación. Ahora lo arreglé y mejoré un poco el feedback.

¡Saludos!

**Comment by cruz** [comment]
Me había faltado un paso de grabación. Ahora sí debería estar.
