### ISSUE TITLE
Interrupciones

### ISSUE THREAD

**Issue by BenjaPrograma** [IIC2333/Foro-2020-2#60]
Hola! Me entro la duda de como funcionan las interrupciones.
Un proceso READY con menor PID y MISMO deadline que otro proceso que esta en RUNNING se ve interrumpido?

**Comment by KnowYourselves** [comment]
Hola @BenjaPrograma!

No, no debiese, ya que al tener el mismo _deadline_ el proceso con menor PID tiene la prioridad de ejecución.

Éxito!

**Comment by BenjaPrograma** [comment]
Me refiero a que el proceso con el mismo deadline y menor PID es el que tiene intenciones de interrumpir al otro. Por ej: Paso a estar ready recien por su start_time, y ve un proceso con mayor PID pero mismo deadline, lo interrumpe entonces?

**Comment by KnowYourselves** [comment]
Ah, mis disculpas, leí mal. 

Se cumple lo mismo, si aparece un proceso `READY` con mismo deadline y menor PID, debiése ocurrir una interrupción.

Éxito!
