### ISSUE TITLE
Duda error de memoria: Malloc.

### ISSUE THREAD

**Issue by nhorellana** [IIC2333/Foro-2020-2#61]
Hola! Al inicializar el struct de Queue estamos teniendo un problema de memoria pero no entendemos que es ni como solucionarlo:

> edf: malloc.c:2379: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
Aborted (core dumped)

Y este es el error que me sale con Valgrind:

[Error](https://imgur.com/a/S1o0TAr)

Saben que podria ser o como poder leerlo?

**Comment by KnowYourselves** [comment]
Hola @nhorellana!

Por lo que veo tienen varios errores de memoria, desde `fopen` hasta cuando están creando el `Queue`. Les recomiendo revisar secciones de su códgio de a poco y ver que no tengan errores de memoria, por ej, probando solo abriendo el archivo, probando solo creando el `Queue`, ya que el error que me dices puede ser consecuencia directa de los errores ya presentes en el programa.

Éxito!
