### ISSUE TITLE
Orden Archivo Output

### ISSUE THREAD

**Issue by ararojas** [IIC2333/Foro-2020-2#63]
Hola!
En el archivo output los procesos y sus estadísticas se tienen que escribir en un orden específico? Quiero decir, debe escribirse primero el primer proceso en terminar y continuar con ese orden? O escribirse según orden de PID? O da lo mismo?
Gracias y saludos,
Araceli

**Comment by KnowYourselves** [comment]
Hola @ararojas!

Da lo mismo el orden, mientras cada proceso tenga una línea y esa línea contenga la información correcta en el orden correcto todo bien.

Éxito!

**Comment by ararojas** [comment]
Gracias @KnowYourselves !!
