### ISSUE TITLE
¿Turnaround y response time?

### ISSUE THREAD

**Issue by clementeross** [IIC2333/Foro-2020-2#64]
Hola!

Duda cortita. Como dice la pregunta, ¿a qué se refieren los "turnaround" y "response" time? Feliz si lo explican de la misma manera en que está explicado el "waiting" time en el enunciado.

Gracias!

**Comment by KnowYourselves** [comment]
Hola @clementeross!

El _response time_ es cuanto tiempo el proceso estuvo esperando a ser atendido por una CPU por primera vez.
El _turnaround time_ es cuanto tiempo paso entre que el proceso paso a estar en estado `READY` por primera vez, hasta que terminó.

Éxito!
