### ISSUE TITLE
El deadline es absoluto o relativo?

### ISSUE THREAD

**Issue by fjquintana** [IIC2333/Foro-2020-2#65]
Hola!

En la ayudantia me parece haber escuchado que el deadline corresponde al tiempo absoluto desde que inicia el programa principal, pero en el enunciado de la tarea dice que el deadline es el "tiempo maximo que tiene el proceso para terminar todas sus ´
rafagas desde su llegada al sistema". Entonces, por ejemplo, si tenemos un proceso con tiempo de llegada 50 y deadline 100, eso significa que su deadline termina en 50 segundos mas (absoluto) o en 100 segundos mas (o sea tiempo global = 150)?

Gracias!

**Comment by KnowYourselves** [comment]
Hola @fjquintana!

Es un tiempo absoluto, para el tiempo `100` nos gustaría que el proceso haya ejecutado todo, que esta `50` ticks del tiempo `50`.

Éxito!

**Comment by fjquintana** [comment]
Perfecto, muchas gracias!
