### ISSUE TITLE
Burst timer en interrupciones

### ISSUE THREAD

**Issue by cirey1** [IIC2333/Foro-2020-2#66]
Hola,

Tengo una duda al respecto de los tiempos de bursts cuando se interrumpe un proceso. Si tengo un proceso corriendo en una CPU y tengo otro en estado "Ready" con mayor prioridad (Deadline menor). Al momento de hacer la interrupción, debo descontar del contador de tiempo del burst?

Ejemplo.

Proceso 1 (Running)
- tiempo restante: 4

Proceso 2 (Ready)
- tiempo restante: 3

Durante la iteración, debe reducir el número del proceso ya corriendo y quedar así?

Proceso 1 (Ready)
- tiempo restante burst: 3 (4 - 1)

Proceso 2 (Running)
- tiempo restante: 3

**Comment by KnowYourselves** [comment]
Hola @cirey1!

Es súper simple, al inicio de cada tick se hacen todos los cambios de estado correspondientes, al final de tick se actualizan las ráfagas. Por ejemplo, al inicio del tick `t` un proceso interrumpió a otro y al final del tick `t` (que es lo mismo que decir inicio del tick `t+1`) se disminuyo en uno la ráfaga del proceso por el cual se realizó la interrupción.

Éxito!

**Comment by rafabusleme** [comment]
> Hola @cirey1!
> 
> Es súper simple, al inicio de cada tick se hacen todos los cambios de estado correspondientes, al final de tick se actualizan las ráfagas. Por ejemplo, al inicio del tick `t` un proceso interrumpió a otro y al final del tick `t` (que es lo mismo que decir inicio del tick `t+1`) se disminuyo en uno la ráfaga del proceso por el cual se realizó la interrupción.
> 
> Éxito!

Según lo que entendí en issues anteriores, cuando a un proceso se le acaba un CPU burst, este cambia inmediatamente de estado. Entonces, también se pueden cambiar estados al final de cada tick. Es correcto pensarlo así o habría que verificar al inicio de cada tick, qué procesos tienen CPU burst en 0 y cambiarlos al estado que corresponda?

**Comment by KnowYourselves** [comment]
Hola @rafabusleme!

El inicio y el final del tick son lo mismo. El inicio de `t+1` es el final de `t`. Lo importante es que no hagas más cosas de las correspondientes en un solo tick.

Éxito!
