### ISSUE TITLE
Archivos de prueba

### ISSUE THREAD

**Issue by vaguila95** [IIC2333/Foro-2020-2#67]
Hola! ¿Sería posible que nos dieran un input.txt con el output.csv correspondiente? Principalmente para revisar que estemos calculando correctamente los tiempos :smile:

**Comment by KnowYourselves** [comment]
Hola @vaguila95!

Parte de lo que estamos evaluando es que ustedes mismos corroboren que están calculando correctamente los tiempos. Si les fuéramos a pasar archivos de prueba habrían dos casos:

1. Cubren todos los posibles casos borde, en tal caso les estamos haciendo trabajo que queremos evaluarles.
2. No cubren todos los posibles casos borde, en tal caso les estamos dando un falso sentido de seguridad.

Esas son las principales razones por las cuales preferimos no darles archivos de prueba. Lo que si, no tenemos ningún problema con que uds creen sus propios archivos de prueba y compartan entre grupos los resultados y los discutan.

Éxito!
