### ISSUE TITLE
Duda procesos WAITING a READY

### ISSUE THREAD

**Issue by ghost** [IIC2333/Foro-2020-2#68]
Hola, te tengo una duda en el momento en que un proceso pasa de estado WAITING a estado READY. Implementamos que el conteo de burst se haga al final de cada tick. Entonces cuando se acaban los burst de un proceso que estaba WAITING y pasa a READY debemos ver en ese mismo tick si meterlo en la CPU o puede esperar al siguiente?

**Comment by KnowYourselves** [comment]
Hola @tomas-burotto!

Los cambios de estado son inmediatos, por lo cual si al inicio/final de un tick un proceso pasa de `WAITING` a `READY` y hay espacio para el en la CPU, debiese pasar inmediatamente a estado `RUNNING`.

Éxito!

**Comment by ghost** [comment]
Perfecto gracias!
