### ISSUE TITLE
Interrupciones

### ISSUE THREAD

**Issue by lothardp** [IIC2333/Foro-2020-2#69]
Hola! Las interrupciones que hay que escribir en el archivo de salida son solo las veces que el scheduler saca el proceso "a la fuerza" (de estado running a ready)? O también hay que contar las interrupciones "naturales", de estado running a waiting por un burst o la de estado running a  finished porque terminó el proceso?. Gracias!

**Comment by KnowYourselves** [comment]
Hola @lothardp!

Las interrupciones "naturales" que describes, no serían interrupciones, ya que el mismo proceso fue quien bajo su propio acorde pasó a una ráfaga I/O. En ese sentido se cumple lo primero que dices, solo se consideran los cambios de `RUNNING` a `READY`.

Éxito!
