### ISSUE TITLE
CRSH debe esperar a que termine el programa llamado con crexec?

### ISSUE THREAD

**Issue by viantirreau** [IIC2333/Foro-2020-2#7]
Hola! 
Junto a la duda del título, para el reporte de ejecuciones anteriores con `crlist`, si siempre esperamos a que terminen los programas invocados por `crexec`, entonces no habría «programas ejecutando en ese momento». Solo podríamos reportar el tiempo de ejecución, PID y el nombre de programas que ya terminaron. Es correcto entenderlo así?

Muchas gracias y buen día!

**Comment by KnowYourselves** [comment]
Hola @viantirreau!

No, no es correcto. Me explico.

Cuando usas `crexec` creas un nuevo proceso por lo cual despues de hacer el comando el programa sigue como si nada. Luego cuando haces `crlist` debes chequear cada uno de los procesos hijos y si es que siguen vivos (se puede hacer wait sin quedarse esperando para siempre) imprimes su data.

Esto quiere decir que después de `crexec` un proceso puede quedar como _zombie_ y va a ser esperado cuando hagas `crlist`.

Espero se entienda.

Éxito!

**Comment by viantirreau** [comment]
Aah perfecto! Gracias por tu respuesta @KnowYourselves!

Para confirmar, cuando uso `crexec command`, entonces se ejecuta como "detached", no lo queda esperando y puede seguir recibiendo input instantáneamente. Así, solo si usamos `crlist` es que vamos a saber si el proceso hijo terminó o sigue ejecutando, y también devuelve instantáneamente el control al usuario de `crsh`.

Gracias nuevamente!

**Comment by KnowYourselves** [comment]
Exactamente.

Solo recuerda que cuando ejecutas `crlist` y el proceso terminó, no es necesario que muestres información de él (si quieres puedes avisar que terminó, pero no es necesario).

Éxito!

**Comment by Bneya** [comment]
Hola, una duda de lo mismo. Si por ejemplo el programa sum de la carpeta programs, simplemente suma y luego termina inmediatamente, ¿significa que no debería aparecer nunca en **crlist** a no ser que yo fuera lo suficientemente rápido como para alcanzar a revisar la lista en los 0.1s que demora su ejecución? ¿O si reviso la lista crlist después de 2 segundos de ejecutarlo, debeía aparecerme que lleva 2 segundos ejecutándose y se queda ahí hasta que yo explícitamente lo mate?

Gracias.

**Comment by Cadagan** [comment]
En esa misma linea, en el enunciado dice para _crlist_:  _"listado de todos los programas **que fueron ejecutados**
desde crsh **y se encuentran ejecutando**"_ pero por lo que dices @KnowYourselves entonces solo debemos mostrar los que estan corriendo cuando ejecuto _crlist_ ? y por otro lado, los zombies y huerfanos tambien debemos ponerlos o no?

**Comment by KnowYourselves** [comment]
Hola @Bneya!

Sería lo primero. Es prácticamente imposible que el programa `sum` se demore lo suficiente como para que alcances a hacer `crlist` antes de que termine. Por lo cual en la práctica no debiese aparecer nunca en `crlist`, ya que cuando ejecutes este comando, te habrás dado cuenta que ya terminó.

**Comment by KnowYourselves** [comment]
Hola @Cadagan!

En primer lugar **no debiése haber ningún proceso huérfano** ya que por la descripción del programa este debe esperar y/o parar a todos los programas que generó antes de terminar.

Ahora, en cuanto a los procesos _zombie_, en el caso que dice @Bneya, hacer `crexec sum 1 5` crearía un proceso que quedaría como _zombie_ hasta que hagas `crlist` o `crexit`. Finalmente, como un proceso _zombie_ ya terminó su ejecución, este no debiése aparecer al momento de hacer `crlist`.

**Comment by Cadagan** [comment]
Aaa ya, perfecto, entonces los procesos que ya terminaron no los debemos mostrar, muchas gracias! :)

**Comment by cchauriye** [comment]
Hola! 

Si en command yo ingresara un proceso y le pongo un sleep de X segundos, durante ese tiempo el proceso debiese aparecer en `crlist`?

**Comment by KnowYourselves** [comment]
Hola @cchauriye!

Si ejecutas un programa que tiene `sleep` mediante `crexec` no afectaría en nada. Simplemente debieses ver que el programa se está ejecutando si haces `crlist` antes de que termine.

Éxito!

**Comment by cchauriye** [comment]
Gracias!

**Comment by NachoJuanDev** [comment]
Hola! estaba leyendo unas issues y estas observaciones me generaron dudas:

> Sería lo primero. Es prácticamente imposible que el programa `sum` se demore lo suficiente como para que alcances a hacer `crlist` antes de que termine. Por lo cual en la práctica no debiese aparecer nunca en `crlist`, ya que cuando ejecutes este comando, te habrás dado cuenta que ya terminó.

> Ahora, en cuanto a los procesos _zombie_, en el caso que dice @Bneya, hacer `crexec sum 1 5` crearía un proceso que quedaría como _zombie_ hasta que hagas `crlist` o `crexit`. Finalmente, como un proceso _zombie_ ya terminó su ejecución, este no debiése aparecer al momento de hacer `crlist`.

Esto me genera una duda. El enunciado para el comando `crlist` dice:

![Screenshot from 2020-09-01 22-58-46](https://user-images.githubusercontent.com/37151320/91927139-c27e3a00-eca6-11ea-86cb-665b91483eae.png)
![Screenshot from 2020-09-01 22-59-45](https://user-images.githubusercontent.com/37151320/91927171-d32eb000-eca6-11ea-95fb-94a4530dbf6f.png)


Por mi implementación, muestro una lista de **todos** los programas que fueron ejecutados con crsh tantos los que ya terminaron como los que aún no terminan. Si ya terminaron muestro el tiempo que duró su ejecución y si aún no terminan muestro un estado que dice que se está ejecutando y el tiempo que lleva. 

Si me baso en las observaciones de @KnowYourselves esta implementación no sería del todo correcta, pero si me baso en el enunciado eso sería exactamente lo que estarían pidiendo. Entonces, ¿Qué debemos mostrar al usuario?.

En cualquier caso, mi implementación no genera ningún proceso huerfano ni zombie y no tendría problema en omitir los programas que ya terminaron.  

Saludos.

**Comment by KnowYourselves** [comment]
Hola @nacho-11!

Es cierto que el enunciado quedó un poco ambigüo en ese sentido, pero te pido que **no muestres los procesos que ya terminaron** para que sea parejo para todos.

Éxito!

**Comment by NachoJuanDev** [comment]
Dale, lo arreglo altiro :ok_hand:
