### ISSUE TITLE
I1: Aclaraciones de enunciado

### ISSUE THREAD

**Issue by cruz** [IIC2333/Foro-2020-2#71]
El contenido de esta issue se actualizará con las preguntas que se reciban. Para formular una nueva pregunta, responder a esta issue. Se intentará responder en el tiempo más breve posible.

**Pregunta 3: Para el mejor scheduling, ¿nos referimos exclusivamente a las métricas del proceso p0? (ie. cuál alternativa le conviene al proceso p0), ¿O hay que ver cuál brinda mejor scheduling a modo general?**

De manera general. El proceso p0 es un ejemplo de cómo se comportaría con cualquier proceso.

**Pregunta 3: En la misma línea de la duda de mi compañero, cuando buscamos cambiar el quantum, ¿se hace solo para el proceso p0 o para todos los procesos que en ese momento estén en la cola?**

Piensen que todos los procesos se comportan así. Estoy preguntando qué conviene más hacer con el quantum que sobra. ¿Lo reseteo o sigo ocupando lo que queda?

**Pregunta 3: i. La actualización del quantum se realiza solo en la primera cola?**

Sí, solo en la primera cola. Igual no cambia mucho si lo consideran para las otras colas, pero en este caso solo para la primera.

**Pregunta 3. ii. La actualización se vuelve a aplicar si es que se continúa abandondando la CPU antes que se acabe su nuevo quantum?**

Sí

**Pregunta 3b. ¿La interactividad del sistema, se refiere a la interactividad entre procesos o de los procesos con I/Os?**

Interactividad de procesos: eso es que usan harto I/O.

**Pregunta 5a. Cuando se habla de acción atómica, es lo mismo que instrucción atómica?** 

No, una instrucción atómica es provista por el _hardware_ (no hablo de esas). Acciones atómicas son acciones que deben ocurrir sin interrupción. Piensen que pasa si la CPU está ejecutando "algo" del sistema operativo y la interrumpen.

**Pregunta 4: a qué se refiere cuando se pregunta "¿Qué ocurre con el uso de CPU?". Se refiere al % de CPU que se utiliza en cada instante de tiempo? La velocidad de ejecución?**

Uso de CPU. Lo primero. Se refiere al porcentaje de la CPU que está siendo utilizada.

**Pregunta 6b: Cuando se pregunta sobre el cumplimiento de propiedades de las tres implementaciones. ¿Se refiere a la implementación del lock mismo? ¿O a los threads que implementan esos locks para entrar a su SC?**

Se refiere a la implementación del *lock*. Cada implementación de *lock* que se muestra es una solución propuesta al problema de la sección crítica, y se pide indicar si cumple o no con las propiedades (exclusión mutua, progreso, espera acotada)

**Comment by bpardobravo** [comment]
Duda en la pregunta 3: Para el mejor scheduling, ¿nos referimos exclusivamente a las métricas del proceso p0? (ie. cuál alternativa le conviene al proceso p0), ¿O hay que ver cuál brinda mejor scheduling a modo general?

**Comment by Franco1605** [comment]
Duda en la pregunta 3: En la misma línea de la duda de mi compañero, cuando buscamos cambiar el quantum, ¿se hace solo para el proceso p0 o para todos los procesos que en ese momento estén en la cola?

**Comment by nicoparraguez** [comment]
+1 a las dudas de la pregunta 3

**Comment by mframos3** [comment]
Dudas en la pregunta 3: 
- 1. La actualización del quantum se realiza solo en la primera cola? 
- 2. La actualización se vuelve a aplicar si es que se continúa abandondando la CPU antes que se acabe su nuevo quantum?

**Comment by tpcantergiani** [comment]
Duda 3b:
¿La interactividad del sistema, se refiere a la interactividad entre procesos o de los procesos con I/Os?

**Comment by VicenteMerino** [comment]
P5 a. Cuando se habla de acción atómica, es lo mismo que instrucción atómica?

**Comment by clementeross** [comment]
P4: a qué se refiere cuando se pregunta "¿Qué ocurre con el uso de CPU?". Se refiere al % de CPU que se utiliza en cada instante de tiempo? La velocidad de ejecución?

**Comment by Marialuisaclaro** [comment]
P6.b) Cuando se pregunta sobre el cumplimiento de propiedades de las tres implementaciones. ¿Se refiere a la implementación del lock mismo? ¿O a los threads que implementan esos locks para entrar a su SC?

**Comment by BenjaPrograma** [comment]
Respecto de la pregunta 5.a) Quieren que mencionemos acciones respecto a threads que necesitan ocurrir de manera atomica, o que mencionemos ejemplos de operaciones atomicas del s.o?
