### ISSUE TITLE
AC03 - Pregunta 19 (y 20?)

### ISSUE THREAD

**Issue by naviera** [IIC2333/Foro-2020-2#72]
Con respecto al test de schedulability en RMS, no entiendo qué sentido tiene agregar un proceso para que el conjunto sea ejecutable, lo plantearé de la siguiente forma para no dar la respuesta.
Para <img src="https://render.githubusercontent.com/render/math?math=u_A"> y <img src="https://render.githubusercontent.com/render/math?math=u_B"> cualquieras necesitamos:
<img src="https://render.githubusercontent.com/render/math?math=u_A %2B u_B \leq 0.8284">
Al agregar un proceso C con uso de CPU <img src="https://render.githubusercontent.com/render/math?math=u_C"> necesitamos:
<img src="https://render.githubusercontent.com/render/math?math=u_A%2B u_B %2B u_C \leq 0.7798">
Por lo tanto, agregar un proceso en este caso no puede ayudar a pasar el test (que no coincide con los resultados que obtuve en la actividad).
Agradecería si le pueden echar un ojo :)

**Comment by cruz** [comment]
Hola @naviera 
En primer lugar, mis disculpas por la demora en esta respuesta. Talvez no queda clara la explicación de una de las alternativas. Lo que dices es cierto: si tengo dos procesos que no pasan el test bajo un modelo, al agregar un tercer modelo tampoco lo harán. Lo que dice la alternativa:

> Es posible agregar un tercer proceso de manera que el conjunto sea ejecutable bajo RMS o bajo EDF.

es que agregando un tercer proceso, podría funcionar en al menos uno de dos (RMS o EDF). Si te ya falló con dos procesos para uno de los schedulers, puede ser que para el otro scheduler sí se pueda (o bien, que no se pueda).

Traté de explicarlo si dar la respuesta directamente (aunque no sé si lo conseguí, jaja).
