### ISSUE TITLE
Actividad 03 Pregunta 11

### ISSUE THREAD

**Issue by IriSalazar** [IIC2333/Foro-2020-2#73]
Hola :D 
No me queda claro a que se refiere la pregunta cuando nos pide lo siguiente: 

_"En el caso de un proceso que no alcanza a terminar durante su quantum, calcule primero el response time promedio de cada proceso considerando todas las veces que pasó a la cola ready, y luego calcule el promedio de todos los procesos."_

He intentado de 2 formas distintas y aún no me sale, ¿podrían explicármelo por favor?

**Comment by marianaortega1** [comment]
+1

**Comment by fjlopez7** [comment]
Si todavía están con dudas me sirvió esta [guía](http://www.redtauros.com/Clases/Gestion_SO/taller_1.pdf) para realizar los cálculos.

**Comment by cruz** [comment]
Hola @IriSalazar @mariana-ortega ,
En primer lugar, disculpas por la demora. La idea es:
* Para cada proceso, buscar todas las veces que ha pasado esperando en la cola *ready*. Cada uno de estos tiempos es el tiempo desde que salió de ejecución (si es su primera ejecución, el tiempo desde que llegó a la cola) hasta que volvió a hacer elegido.
* Sacar el promedio de tiempo que esperó
* Cuando se tenga el valor para cada uno de los 5 procesos, calcular el promedio de ellos

Lo que es puede ser confuso es que, cuando empezó la ejecución, el P1 era el primer en la cola, por lo tanto para su primer turno esperó 0. Si para su segundo turno esperó 40, entonces su tiempo promedio de espera es 20. Es posible que hayan considerado que su tiempo de espera fue 40, si consideran que la primera vez "no esperó".

He actualizado la pregunta para que lo considere bueno de ambas maneras. Espero que eso las ayude, ya que coincido en que ese primer caso es muy particular.
