### ISSUE TITLE
Uso de librerías o header files externos

### ISSUE THREAD

**Issue by Bneya** [IIC2333/Foro-2020-2#74]
Buenas.

¿Está permitido usar algún tipo de header file externo importado que implemente algo por comodidad y no del funcionamiento interno de la tarea?
Por ejemplo, un .h que implementa hashing en C

Gracias.

**Comment by IchottMano** [comment]
Hola!

Esperamos que usen la librería estándar de C, sin embargo podríamos permitir otras librerías, siempre y cuando nos expliques:

- Que librería es
- Que hace la librería
- Para qué quieren usar la librería
- Como instalarla (por defecto probablemente no la tenemos instalada)

Con esos datos podemos darte una respuesta.

Saludos!
