### ISSUE TITLE
AC05 - Pregunta 13

### ISSUE THREAD

**Issue by Franco1605** [IIC2333/Foro-2020-2#76]
Hola ! Creo que estoy calculando mal las direcciones físicas porque llevo muchas respondiendo SEGFAULT (y dudo que todas sean así). Por lo que, me gustaría aclarar el traspaso de una dirección virtual a una física en esa pregunta:
Supongamos que tengo la dirección virtual 0x3002 = 0b11000000000010.
Preguntas:
 ¿El bit de segmento sería 11 o 10 ? 
 Si paso del hexadecimal a binario y este no cumple con la cantidad de bits totales, ¿se rellena con 0 a la izquierda ? (por 
 ejemplo, poner tantos ceros como sea necesario para llegar a 14).

Creo que estoy un poco confundido. Gracias de antemano.

**Comment by cruz** [comment]
Hola @Franco1605 ,
En tu ejemplo, el segmento sería 11. Para contar los bit, es mejor contarlos de derecha a izquierda. Si necesitas más bit, se rellenan a la izquierda con 0s. Otra manera es convertir todos los hexadecimales a binario, y luego eliminar de la izquierda los 0's que no necesites. En este caso, puedes transformarlo como:

```
0x3002 --> 0b0011 0000 0000 0010
```

Pero ahí hay 16 bit. Como necesitas 14 bit, entonces la transformación debería ser:

```
0x3002 --> 0b11 0000 0000 0010
```

Si dicen que son 14 bit, y los últimos 12 son de desplazamiento, entonces los dos primeros de esos 14 bit son 11.

Espero que eso ayude. Si no, escribe por aquí, y contesto de nuevo (pero más rápido ahora).

**Comment by Franco1605** [comment]
Entiendo. Ahora, con ese mismo ejemplo que se da en la actividad (0x3002), estaría apuntando al segmento 3. Pero, solo tengo los segmentos 0, 1 y 2. ¿cómo debería tratar ese caso entonces :o?

**Comment by cruz** [comment]
En ese caso sí es un `Segmentation Fault` :)
