### ISSUE TITLE
os_bitmap, impresión en hexadecimal

### ISSUE THREAD

**Issue by diegoheg** [IIC2333/Foro-2020-2#77]
Hola, cuando nos piden imprimir un bloque o todo el bitmap en hexadecimal ¿De qué manera debemos imprimirlo? tomando cada byte del bitmap como un número y concatenando cada hexadecimal de cada byte o todo el bitmap como un solo número y transformando ese número a hexadecimal. Si es la segunda opción ¿El número como lo tratamos? debemos darlo vuelta para que la posición 0 sea 2^0 o tomarlo como viene.

Gracias!!!

**Comment by IchottMano** [comment]
Hola!

Ya que el disco se trabaja en big endian, ambas opciones son lo mismo. Recomiendo sí ir tomando los bytes de a uno y eso transformarlo en dos chars que sean mas trabajables.

Nosotros esperamos que, por ejemplo, si un byte del bitmap es C o 1100 yo espero ver 2 bloques ocupados seguidos por 2 bloques libres en el disco.

Saludos!
