### ISSUE TITLE
Múltiples bloques índices para archivos

### ISSUE THREAD

**Issue by diegoheg** [IIC2333/Foro-2020-2#79]
Hola, con nuestro grupo tenemos la duda de como comprobar que un archivo tiene más de un bloque índice cuando está escrito en el disco. Hasta ahora estamos haciendo la comprobación mediante el tamaño, pero podríamos asumir que cuando el archivo no tiene más bloques índice el puntero hacia un siguiente bloque índice es 0 ¿Esta suposición es correcta?¿O es posible que un archivo con un solo bloque índice posea un puntero a otro bloque índice que no le pertenece?

**Comment by IchottMano** [comment]
Hola!

Deben tener en cuenta que siempre puede haber basura escrita en el disco, por ejemplo podría haber un número distinto a cero en el puntero sin que el puntero sea válido. Todas las comprobaciones tienen que ser tomando en cuenta el tamaño del archivo.

Saludos!
