### ISSUE TITLE
Que make file tenemos que subir al servidor?

### ISSUE THREAD

**Issue by lzalaquett** [IIC2333/Foro-2020-2#8]
Hola, en el anuncio de canvas nos dieron 3 archivosm entre ellos un Makefile. Pero además, al descomprimir Base, ahi dendtro hay otro Makefile. Cual tenemos que utilizar? o ambos son lo mismo? porque al parecer tienen algunas diferencias

**Comment by KnowYourselves** [comment]
Hola @lzalaquett!

Son el mismo Makefile pero con diferencia en su configuración. Si quieres saber como funciona este Makefile puedes ver la ayudantía pasada. 

En cuanto a tu pregunta, debes subir cualquiera sea el Makefile que utilices, no es necesario que utilices el Makefile que te damos si no quieres.

Éxito!

**Comment by lzalaquett** [comment]
Muchas gracias!!!
