### ISSUE TITLE
Escribir bits en archivo

### ISSUE THREAD

**Issue by marianaortega1** [IIC2333/Foro-2020-2#80]
Hola!

Tenemos un arreglo de tamaño 8 de unsigned chars (unsigned char bit[8]) que contienen los 8 bits de un byte y queremos escribirlo en un archivo ocupando fwrite. Probamos todo lo que encontramos en internet y no logramos de ninguna manera modificar el archivo.

Podrían ayudarnos a entender cómo ocupar fwrite para escribir bytes o bits en un archivo? 

Gracias de antemano y saludos!

**Comment by KnowYourselves** [comment]
Hola @mariana-ortega!

Primero con lo más importante **no existen los _bits_ como tipo en C, el _byte_ es la unidad atómica del lenguaje**. Esto quiere decir que lo más que puedes subdidir algo es un byte, que no es nada más que un `unsigned char` cuyo valor esta entre 0  y 255. 

Es decir, tu vas a leer _bytes_ y escribir _bytes_, de hecho, el arreglo que defines `unsegined char bit[8]` es un arreglo de 8 bytes solo que sus valores van a ser `00000001` o `00000000`. 

Luego para usar `fwrite`, le pasas un buffer con bytes y le dices cuantos de ellos quieres escribir, eso es todo.

Lo que si debes hacer es leer _bytes_ y modificar sus _bits_ esto se reduce a ocupar operadores _bitwise_ para cambiar _bits_ específicos de un _byte_ y luego escribir el resultado al archivo. Piensa que cambiar un _bit_ es tan solo cambiar el _byte_ de un número a otro.

Éxito!
