### ISSUE TITLE
Detalle código base

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2333/Foro-2020-2#9]
![Screenshot from 2020-08-26 20-37-30](https://user-images.githubusercontent.com/47841749/91370544-a5e08e80-e7dc-11ea-8dc3-c2f8e8df55ea.png)

Hola, creo que en el código base faltó mostrar como usar argv, a qué tipo corresponde y cómo se printearía?

**Comment by KnowYourselves** [comment]
Hola @VicenteMerino!

Acabo de descargar el código base y veo lo sig:

![image](https://user-images.githubusercontent.com/26102039/91370877-826a1380-e7dd-11ea-9993-1a2ab862a0f0.png)

Ahí se puede ver que `argv` corresponde a un _array_ de _strings_ y se _printea_ con `%s`.

Éxito!

**Comment by VicenteMerino** [comment]
Buena no le había puesto atención a lo que hacía esa lína. Gracias
